-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
	vim.cmd("highlight clear")
end
vim.g.colors_name = "bamboo"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { fg = "#70c2be" })
hi(0, "@attribute.typescript", { fg = "#57a5e5" })
hi(0, "@character.special", { link = "Special" })
hi(0, "@comment", { fg = "#e2c792", italic = true })
hi(0, "@comment.error", { bg = "#e75a7c", bold = true, fg = "#111210" })
hi(0, "@comment.note", { bg = "#57a5e5", bold = true, fg = "#111210" })
hi(0, "@comment.todo", { link = "Todo" })
hi(0, "@comment.warning", { bg = "#ff9966", bold = true, fg = "#111210" })
hi(0, "@constant.builtin", { link = "Constant" })
hi(0, "@constant.macro", { link = "Constant" })
hi(0, "@constructor", { bold = true, fg = "#dbb671" })
hi(0, "@constructor.lua", { fg = "#dbb671" })
hi(0, "@diff.delta", { link = "DiffChange" })
hi(0, "@diff.minus", { link = "DiffDelete" })
hi(0, "@diff.plus", { link = "DiffAdd" })
hi(0, "@error", { link = "Error" })
hi(0, "@function.builtin", { fg = "#ff9966" })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { fg = "#bfa6d9" })
hi(0, "@function.method", { link = "Function" })
hi(0, "@function.method.call", { link = "Function" })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.conditional.ternary", { link = "Operator" })
hi(0, "@keyword.coroutine", { link = "Keyword" })
hi(0, "@keyword.debug", { link = "Keyword" })
hi(0, "@keyword.directive", { link = "PreProc" })
hi(0, "@keyword.directive.define", { bold = true, fg = "#aaaaff" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.operator", { link = "Keyword" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.return", { link = "Keyword" })
hi(0, "@keyword.storage", { link = "StorageClass" })
hi(0, "@lsp.mod.readonly", { link = "@constant" })
hi(0, "@lsp.mod.static.rust", { link = "@lsp.typemod.variable.static" })
hi(0, "@lsp.mod.typeHint", { link = "@type" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinAttribute", { link = "@attribute" })
hi(0, "@lsp.type.builtinConstant", { link = "@constant.builtin" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.class.markdown", {})
hi(0, "@lsp.type.comment", {})
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.derive", { link = "@constructor" })
hi(0, "@lsp.type.deriveHelper", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.event", { link = "Label" })
hi(0, "@lsp.type.formatSpecifier", { link = "@punctuation.special" })
hi(0, "@lsp.type.generic", { link = "@markup" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.lifetime", { link = "@keyword.storage" })
hi(0, "@lsp.type.macro", { link = "Macro" })
hi(0, "@lsp.type.magicFunction", { link = "@function.builtin" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.operator.cpp", {})
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.selfTypeKeyword", { link = "@type" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.typeParameter", { link = "@type" })
hi(0, "@lsp.type.unresolvedReference", { sp = "#e75a7c", undercurl = true })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.type.variable.rust", { fg = "#f1e9d2" })
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.function.readonly", { link = "@function.method" })
hi(0, "@lsp.typemod.generic.attribute", { link = "@keyword" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.keyword.injected", { link = "@keyword" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.readonly", { link = "@function.method" })
hi(0, "@lsp.typemod.method.static.rust", { link = "@function" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.parameter.mutable", { fg = "#e28899" })
hi(0, "@lsp.typemod.parameter.readonly", { fg = "#e8947a" })
hi(0, "@lsp.typemod.property.readonly", { fg = "#80bc99" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.struct.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.typeAlias.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.variable.callable", { link = "@function" })
hi(0, "@lsp.typemod.variable.constant.rust", { link = "@constant" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.global", { link = "@variable.global" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@lsp.typemod.variable.mutable", { fg = "#ccd6ae" })
hi(0, "@lsp.typemod.variable.static", { fg = "#96c7ef" })
hi(0, "@lsp.typemod.variable.static.rust", {})
hi(0, "@markup.environment", { bold = true, fg = "#70c2be" })
hi(0, "@markup.environment.name", { link = "Type" })
hi(0, "@markup.heading", { bold = true, fg = "#ff9966" })
hi(0, "@markup.heading.1", { bold = true, fg = "#e75a7c" })
hi(0, "@markup.heading.1.marker", { link = "@markup.heading" })
hi(0, "@markup.heading.2", { bold = true, fg = "#dbb671" })
hi(0, "@markup.heading.2.marker", { link = "@markup.heading" })
hi(0, "@markup.heading.3", { bold = true, fg = "#8fb573" })
hi(0, "@markup.heading.3.marker", { link = "@markup.heading" })
hi(0, "@markup.heading.4", { bold = true, fg = "#70c2be" })
hi(0, "@markup.heading.4.marker", { link = "@markup.heading" })
hi(0, "@markup.heading.5", { bold = true, fg = "#57a5e5" })
hi(0, "@markup.heading.5.marker", { link = "@markup.heading" })
hi(0, "@markup.heading.6", { bold = true, fg = "#aaaaff" })
hi(0, "@markup.heading.6.marker", { link = "@markup.heading" })
hi(0, "@markup.italic", { fg = "#f1e9d2", italic = true })
hi(0, "@markup.italic.markdown_inline", { fg = "#ff9966", italic = true })
hi(0, "@markup.link", { link = "Tag" })
hi(0, "@markup.link.label", { link = "Tag" })
hi(0, "@markup.link.url", { fg = "#70c2be", italic = true, underline = true })
hi(0, "@markup.list", { link = "Special" })
hi(0, "@markup.list.checked", { bold = true, fg = "#dbb671" })
hi(0, "@markup.list.unchecked", { bold = true, fg = "#838781" })
hi(0, "@markup.math", { fg = "#96c7ef" })
hi(0, "@markup.quote", { fg = "#bab8aa" })
hi(0, "@markup.raw", { fg = "#8fb573" })
hi(0, "@markup.raw.block", { link = "@markup.raw" })
hi(0, "@markup.raw.delimiter", { fg = "#838781" })
hi(0, "@markup.strikethrough", { fg = "#f1e9d2", strikethrough = true })
hi(0, "@markup.strikethrough.markdown_inline", { fg = "#ff9966", strikethrough = true })
hi(0, "@markup.strong", { bold = true, fg = "#f1e9d2" })
hi(0, "@markup.strong.markdown_inline", { bold = true, fg = "#ff9966" })
hi(0, "@markup.underline", { fg = "#f1e9d2", underline = true })
hi(0, "@module", { fg = "#96c7ef", italic = true })
hi(0, "@module.builtin", { link = "@variable.builtin" })
hi(0, "@none", { fg = "#f1e9d2" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@property", { link = "@variable.member" })
hi(0, "@punctuation.bracket", { link = "Delimiter" })
hi(0, "@punctuation.delimiter", { link = "Delimiter" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@string.documentation", { link = "@comment" })
hi(0, "@string.escape", { fg = "#f08080" })
hi(0, "@string.regexp", { link = "Constant" })
hi(0, "@string.special", { link = "Special" })
hi(0, "@string.special.path", { fg = "#96c7ef", underline = true })
hi(0, "@string.special.symbol", { link = "@variable.member" })
hi(0, "@string.special.url", { fg = "#70c2be", italic = true, underline = true })
hi(0, "@tag", { fg = "#aaaaff" })
hi(0, "@tag.attribute", { link = "@variable.member" })
hi(0, "@tag.builtin", { link = "@tag" })
hi(0, "@tag.delimiter", { link = "Delimiter" })
hi(0, "@type.builtin", { link = "Type" })
hi(0, "@type.definition", { link = "Type" })
hi(0, "@type.qualifier", { fg = "#aaaaff", italic = true })
hi(0, "@variable", { fg = "#f1e9d2" })
hi(0, "@variable.builtin", { fg = "#e75a7c" })
hi(0, "@variable.global", { fg = "#f098ad" })
hi(0, "@variable.member", { fg = "#70c2be" })
hi(0, "@variable.parameter", { fg = "#f08080", italic = true })
hi(0, "@variable.parameter.builtin", { fg = "#e75a7c", italic = true })
hi(0, "ALEErrorSign", { fg = "#e75a7c" })
hi(0, "ALEInfoSign", { fg = "#70c2be" })
hi(0, "ALEWarningSign", { fg = "#dbb671" })
hi(0, "AerialArrayIcon", { fg = "#dbb671" })
hi(0, "AerialBooleanIcon", { fg = "#ff9966" })
hi(0, "AerialClassIcon", { fg = "#dbb671" })
hi(0, "AerialColorIcon", { fg = "#8fb573" })
hi(0, "AerialConstantIcon", { fg = "#ff9966" })
hi(0, "AerialConstructorIcon", { fg = "#57a5e5" })
hi(0, "AerialDefaultIcon", { fg = "#aaaaff" })
hi(0, "AerialEnumIcon", { fg = "#dbb671" })
hi(0, "AerialEnumMemberIcon", { fg = "#ff9966" })
hi(0, "AerialEventIcon", { fg = "#dbb671" })
hi(0, "AerialFieldIcon", { fg = "#70c2be" })
hi(0, "AerialFileIcon", { fg = "#8fb573" })
hi(0, "AerialFolderIcon", { fg = "#96c7ef" })
hi(0, "AerialFunctionIcon", { fg = "#57a5e5" })
hi(0, "AerialInterfaceIcon", { fg = "#8fb573" })
hi(0, "AerialKeyIcon", { fg = "#70c2be" })
hi(0, "AerialKeywordIcon", { fg = "#aaaaff" })
hi(0, "AerialLine", { bg = "#383b35", bold = true, fg = "#aaaaff" })
hi(0, "AerialMethodIcon", { fg = "#57a5e5" })
hi(0, "AerialModuleIcon", { fg = "#96c7ef" })
hi(0, "AerialNamespaceIcon", { fg = "#96c7ef" })
hi(0, "AerialNullIcon", { fg = "#5b5e5a" })
hi(0, "AerialNumberIcon", { fg = "#ff9966" })
hi(0, "AerialObjectIcon", { fg = "#e75a7c" })
hi(0, "AerialOperatorIcon", { fg = "#c5c2ee" })
hi(0, "AerialPackageIcon", { fg = "#dbb671" })
hi(0, "AerialPropertyIcon", { fg = "#70c2be" })
hi(0, "AerialReferenceIcon", { fg = "#ff9966" })
hi(0, "AerialSnippetIcon", { fg = "#bfa6d9" })
hi(0, "AerialStringIcon", { fg = "#8fb573" })
hi(0, "AerialStructIcon", { fg = "#dbb671" })
hi(0, "AerialTextIcon", { fg = "#838781" })
hi(0, "AerialTypeParameterIcon", { fg = "#f08080" })
hi(0, "AerialUnitIcon", { fg = "#dbb671" })
hi(0, "AerialValueIcon", { fg = "#ff9966" })
hi(0, "AerialVariableIcon", { fg = "#e75a7c" })
hi(0, "Bold", { bold = true })
hi(0, "BufferCurrent", { bold = true })
hi(0, "BufferCurrentMod", { bold = true, fg = "#ff9966", italic = true })
hi(0, "BufferCurrentSign", { fg = "#aaaaff" })
hi(0, "BufferInactiveMod", { bg = "#2f312c", fg = "#838781", italic = true })
hi(0, "BufferVisible", { bg = "#252623", fg = "#838781" })
hi(0, "BufferVisibleIndex", { bg = "#252623", fg = "#838781" })
hi(0, "BufferVisibleMod", { bg = "#252623", fg = "#dbb671", italic = true })
hi(0, "BufferVisibleSign", { bg = "#252623", fg = "#838781" })
hi(0, "BufferVisibleTarget", { bg = "#252623", fg = "#838781" })
hi(0, "CmpItemAbbr", { fg = "#f1e9d2" })
hi(0, "CmpItemAbbrDefault", { fg = "#f1e9d2" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#838781", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#5b5e5a" })
hi(0, "CmpItemAbbrMatch", { fg = "#70c2be" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#f1e9d2" })
hi(0, "CmpItemAbbrMatchFuzzy", { fg = "#70c2be", underline = true })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#f1e9d2" })
hi(0, "CmpItemKind", { fg = "#aaaaff" })
hi(0, "CmpItemKindArray", { fg = "#dbb671" })
hi(0, "CmpItemKindBoolean", { fg = "#ff9966" })
hi(0, "CmpItemKindClass", { fg = "#dbb671" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCodeium", { fg = "#f1e9d2" })
hi(0, "CmpItemKindColor", { fg = "#8fb573" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { fg = "#ff9966" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { fg = "#57a5e5" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { fg = "#f1e9d2" })
hi(0, "CmpItemKindDefault", { fg = "#e75a7c" })
hi(0, "CmpItemKindEnum", { fg = "#dbb671" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { fg = "#ff9966" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { fg = "#dbb671" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { fg = "#70c2be" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { fg = "#8fb573" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { fg = "#96c7ef" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { fg = "#57a5e5" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { fg = "#8fb573" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKey", { fg = "#70c2be" })
hi(0, "CmpItemKindKeyword", { fg = "#aaaaff" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { fg = "#57a5e5" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { fg = "#96c7ef" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindNamespace", { fg = "#96c7ef" })
hi(0, "CmpItemKindNull", { fg = "#5b5e5a" })
hi(0, "CmpItemKindNumber", { fg = "#ff9966" })
hi(0, "CmpItemKindObject", { fg = "#e75a7c" })
hi(0, "CmpItemKindOperator", { fg = "#c5c2ee" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindPackage", { fg = "#dbb671" })
hi(0, "CmpItemKindProperty", { fg = "#70c2be" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { fg = "#ff9966" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#bfa6d9", italic = true })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindString", { fg = "#8fb573" })
hi(0, "CmpItemKindStruct", { fg = "#dbb671" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTabNine", { fg = "#f1e9d2" })
hi(0, "CmpItemKindText", { fg = "#838781" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { fg = "#f08080" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { fg = "#dbb671" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { fg = "#ff9966" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#e75a7c" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#838781" })
hi(0, "CmpItemMenuDefault", { fg = "#f1e9d2" })
hi(0, "CocErrorSign", { fg = "#e75a7c" })
hi(0, "CocHintSign", { fg = "#aaaaff" })
hi(0, "CocInfoSign", { fg = "#70c2be" })
hi(0, "CocWarningSign", { fg = "#dbb671" })
hi(0, "ColorColumn", { bg = "#3b4235" })
hi(0, "Comment", { fg = "#5b5e5a", italic = true })
hi(0, "Conceal", { fg = "#5b5e5a" })
hi(0, "Conditional", { fg = "#aaaaff", italic = true })
hi(0, "Constant", { fg = "#ff9966" })
hi(0, "CurSearch", { bg = "#ff9966", fg = "#252623" })
hi(0, "Cursor", { reverse = true })
hi(0, "CursorColumn", { link = "CursorLine" })
hi(0, "CursorLine", { bg = "#2f312c" })
hi(0, "CursorLineNr", { fg = "#f1e9d2" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#a9ff68" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#424242" })
hi(0, "DapUIBreakpointsInfo", { fg = "#a9ff68" })
hi(0, "DapUIBreakpointsPath", { fg = "#00f1f5" })
hi(0, "DapUIDecoration", { fg = "#00f1f5" })
hi(0, "DapUIFloatBorder", { fg = "#00f1f5" })
hi(0, "DapUILineNumber", { fg = "#00f1f5" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#00f1f5" })
hi(0, "DapUIPlayPause", { fg = "#a9ff68" })
hi(0, "DapUIPlayPauseNC", { fg = "#a9ff68" })
hi(0, "DapUIRestart", { fg = "#a9ff68" })
hi(0, "DapUIRestartNC", { fg = "#a9ff68" })
hi(0, "DapUIScope", { fg = "#00f1f5" })
hi(0, "DapUISource", { fg = "#d484ff" })
hi(0, "DapUIStepBack", { fg = "#00f1f5" })
hi(0, "DapUIStepBackNC", { fg = "#00f1f5" })
hi(0, "DapUIStepInto", { fg = "#00f1f5" })
hi(0, "DapUIStepIntoNC", { fg = "#00f1f5" })
hi(0, "DapUIStepOut", { fg = "#00f1f5" })
hi(0, "DapUIStepOutNC", { fg = "#00f1f5" })
hi(0, "DapUIStepOver", { fg = "#00f1f5" })
hi(0, "DapUIStepOverNC", { fg = "#00f1f5" })
hi(0, "DapUIStop", { fg = "#f70067" })
hi(0, "DapUIStopNC", { fg = "#f70067" })
hi(0, "DapUIStoppedThread", { fg = "#00f1f5" })
hi(0, "DapUIThread", { fg = "#a9ff68" })
hi(0, "DapUIType", { fg = "#d484ff" })
hi(0, "DapUIUnavailable", { fg = "#424242" })
hi(0, "DapUIUnavailableNC", { fg = "#424242" })
hi(0, "DapUIWatchesEmpty", { fg = "#f70067" })
hi(0, "DapUIWatchesError", { fg = "#f70067" })
hi(0, "DapUIWatchesValue", { fg = "#a9ff68" })
hi(0, "DapUIWinSelect", { bold = true, ctermfg = 14, fg = "#00f1f5" })
hi(0, "DashboardCenter", { fg = "#70c2be" })
hi(0, "DashboardDesc", { fg = "#aaaaff" })
hi(0, "DashboardFiles", { fg = "#f1e9d2" })
hi(0, "DashboardFooter", { fg = "#833b3b", italic = true })
hi(0, "DashboardHeader", { fg = "#dbb671" })
hi(0, "DashboardIcon", { fg = "#aaaaff" })
hi(0, "DashboardKey", { fg = "#ff9966" })
hi(0, "DashboardMruTitle", { fg = "#70c2be" })
hi(0, "DashboardProjectTitle", { fg = "#70c2be" })
hi(0, "DashboardShortCut", { fg = "#57a5e5" })
hi(0, "Debug", { fg = "#ff9966" })
hi(0, "Delimiter", { fg = "#838781" })
hi(0, "DiagnosticError", { fg = "#e75a7c" })
hi(0, "DiagnosticHint", { fg = "#aaaaff" })
hi(0, "DiagnosticInfo", { fg = "#70c2be" })
hi(0, "DiagnosticUnderlineError", { sp = "#e75a7c", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#aaaaff", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#57a5e5", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#dbb671", undercurl = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#382b2c", fg = "#e75a7c" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#323339", fg = "#aaaaff" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#2d3633", fg = "#70c2be" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#37342b", fg = "#dbb671" })
hi(0, "DiagnosticWarn", { fg = "#dbb671" })
hi(0, "DiffAdd", { bg = "#40531b" })
hi(0, "DiffAdded", { fg = "#8fb573" })
hi(0, "DiffChange", { bg = "#2a3a57" })
hi(0, "DiffDelete", { bg = "#893f45" })
hi(0, "DiffFile", { fg = "#70c2be" })
hi(0, "DiffIndexLine", { fg = "#5b5e5a" })
hi(0, "DiffRemoved", { fg = "#e75a7c" })
hi(0, "DiffText", { bg = "#3a4a67" })
hi(0, "DiffviewCursorLine", { link = "CursorLine" })
hi(0, "DiffviewEndOfBuffer", { link = "EndOfBuffer" })
hi(0, "DiffviewFilePanelCounter", { bold = true, fg = "#aaaaff" })
hi(0, "DiffviewFilePanelDeletions", { fg = "#e75a7c" })
hi(0, "DiffviewFilePanelFileName", { fg = "#f1e9d2" })
hi(0, "DiffviewFilePanelInsertions", { fg = "#8fb573" })
hi(0, "DiffviewFilePanelPath", { fg = "#5b5e5a" })
hi(0, "DiffviewFilePanelRootPath", { fg = "#5b5e5a" })
hi(0, "DiffviewFilePanelTitle", { bold = true, fg = "#57a5e5" })
hi(0, "DiffviewHash", { link = "Constant" })
hi(0, "DiffviewNormal", { link = "Normal" })
hi(0, "DiffviewSignColumn", { link = "SignColumn" })
hi(0, "DiffviewStatusAdded", { fg = "#8fb573" })
hi(0, "DiffviewStatusBroken", { fg = "#e75a7c" })
hi(0, "DiffviewStatusCopied", { fg = "#57a5e5" })
hi(0, "DiffviewStatusDeleted", { fg = "#e75a7c" })
hi(0, "DiffviewStatusLine", { link = "StatusLine" })
hi(0, "DiffviewStatusLineNC", { link = "StatusLineNC" })
hi(0, "DiffviewStatusModified", { fg = "#57a5e5" })
hi(0, "DiffviewStatusRenamed", { fg = "#57a5e5" })
hi(0, "DiffviewStatusTypeChange", { fg = "#57a5e5" })
hi(0, "DiffviewStatusUnknown", { fg = "#e75a7c" })
hi(0, "DiffviewStatusUnmerged", { fg = "#57a5e5" })
hi(0, "DiffviewStatusUntracked", { fg = "#dbb671" })
hi(0, "DiffviewVertSplit", { link = "VertSplit" })
hi(0, "Directory", { fg = "#57a5e5" })
hi(0, "DressingSelectIdx", { link = "Special" })
hi(0, "EndOfBuffer", { fg = "#252623" })
hi(0, "Error", { fg = "#e75a7c" })
hi(0, "ErrorMsg", { bold = true, fg = "#e75a7c" })
hi(0, "Exception", { link = "Keyword" })
hi(0, "Float", { link = "Constant" })
hi(0, "FloatBorder", { bg = "#252623", fg = "#aaaaff" })
hi(0, "FloatFooter", { fg = "#838781" })
hi(0, "FloatTitle", { fg = "#e75a7c" })
hi(0, "FocusedSymbol", { bg = "#383b35", bold = true, fg = "#aaaaff" })
hi(0, "FoldColumn", { fg = "#f1e9d2" })
hi(0, "Folded", { bg = "#2f312c", fg = "#f1e9d2" })
hi(0, "Function", { fg = "#57a5e5" })
hi(0, "FzfLuaBufFlagAlt", { fg = "#98f5ff" })
hi(0, "FzfLuaBufFlagCur", { fg = "#ff4040" })
hi(0, "FzfLuaBufLineNr", { fg = "#00fa9a" })
hi(0, "FzfLuaBufName", { fg = "#ffbbff" })
hi(0, "FzfLuaBufNr", { fg = "#ffebcd" })
hi(0, "FzfLuaHeaderBind", { fg = "#ffebcd" })
hi(0, "FzfLuaHeaderText", { fg = "#ff4040" })
hi(0, "FzfLuaTabMarker", { bold = true, fg = "#ffebcd" })
hi(0, "FzfLuaTabTitle", { bold = true, fg = "#b0e2ff" })
hi(0, "GitConflictAncestor", { bg = "#68217a", bold = true })
hi(0, "GitConflictAncestorLabel", { bg = "#a634c3" })
hi(0, "GitConflictCurrent", { bg = "#3a4a67", bold = true })
hi(0, "GitConflictCurrentLabel", { bg = "#5c76a4" })
hi(0, "GitConflictIncoming", { bg = "#40531b", bold = true })
hi(0, "GitConflictIncomingLabel", { bg = "#66842b" })
hi(0, "GitGutterAdd", { fg = "#8fb573" })
hi(0, "GitGutterChange", { fg = "#57a5e5" })
hi(0, "GitGutterDelete", { fg = "#e75a7c" })
hi(0, "GitSignsAdd", { fg = "#8fb573" })
hi(0, "GitSignsAddLn", { fg = "#8fb573" })
hi(0, "GitSignsAddNr", { fg = "#8fb573" })
hi(0, "GitSignsChange", { fg = "#57a5e5" })
hi(0, "GitSignsChangeLn", { fg = "#57a5e5" })
hi(0, "GitSignsChangeNr", { fg = "#57a5e5" })
hi(0, "GitSignsDelete", { fg = "#e75a7c" })
hi(0, "GitSignsDeleteLn", { fg = "#e75a7c" })
hi(0, "GitSignsDeleteNr", { fg = "#e75a7c" })
hi(0, "GitSignsStagedAdd", { fg = "#475a39" })
hi(0, "GitSignsStagedAddLn", { fg = "#475a39" })
hi(0, "GitSignsStagedAddNr", { fg = "#475a39" })
hi(0, "GitSignsStagedChange", { fg = "#2b5272" })
hi(0, "GitSignsStagedChangeLn", { fg = "#2b5272" })
hi(0, "GitSignsStagedChangeNr", { fg = "#2b5272" })
hi(0, "GitSignsStagedChangedelete", { fg = "#2b5272" })
hi(0, "GitSignsStagedChangedeleteLn", { fg = "#2b5272" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#2b5272" })
hi(0, "GitSignsStagedDelete", { fg = "#732d3e" })
hi(0, "GitSignsStagedDeleteLn", { fg = "#732d3e" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#732d3e" })
hi(0, "GitSignsStagedTopdelete", { fg = "#732d3e" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#732d3e" })
hi(0, "GitSignsUntracked", { fg = "#dbb671" })
hi(0, "GitSignsUntrackedLn", { fg = "#dbb671" })
hi(0, "GitSignsUntrackedNr", { fg = "#dbb671" })
hi(0, "HopNextKey", { bold = true, fg = "#e75a7c" })
hi(0, "HopNextKey1", { bold = true, fg = "#70c2be" })
hi(0, "HopNextKey2", { fg = "#3d73a0" })
hi(0, "HopUnmatched", { fg = "#5b5e5a" })
hi(0, "IblIndent", { fg = "#5b5e5a", nocombine = true })
hi(0, "IblScope", { fg = "#838781", nocombine = true })
hi(0, "IblWhitespace", { fg = "#5b5e5a", nocombine = true })
hi(0, "Identifier", { fg = "#e75a7c" })
hi(0, "IndentBlanklineChar", { fg = "#2f312c", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#838781", nocombine = true })
hi(0, "IndentBlanklineContextSpaceChar", { nocombine = true })
hi(0, "IndentBlanklineContextStart", { bg = "#2f312c" })
hi(0, "IndentBlanklineIndent1", { fg = "#57a5e5" })
hi(0, "IndentBlanklineIndent2", { fg = "#8fb573" })
hi(0, "IndentBlanklineIndent3", { fg = "#70c2be" })
hi(0, "IndentBlanklineIndent4", { fg = "#838781" })
hi(0, "IndentBlanklineIndent5", { fg = "#aaaaff" })
hi(0, "IndentBlanklineIndent6", { fg = "#e75a7c" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#aaaaff" })
hi(0, "Label", { bold = true, fg = "#e75a7c" })
hi(0, "LazyH2", { bold = true, fg = "#57a5e5" })
hi(0, "LazyReasonCmd", { fg = "#8fb573" })
hi(0, "LazyReasonColorscheme", { fg = "#96c7ef" })
hi(0, "LazyReasonFt", { fg = "#dbb671" })
hi(0, "LazyReasonSource", { fg = "#57a5e5" })
hi(0, "LazyReasonStart", { bold = true, fg = "#70c2be" })
hi(0, "LazyReasonTask", { bold = true, fg = "#838781" })
hi(0, "LazyUrl", { link = "@string.special.url" })
hi(0, "LineNr", { fg = "#5b5e5a" })
hi(0, "LspCodeLens", { link = "Comment" })
hi(0, "LspCodeLensSeparator", { fg = "#5b5e5a" })
hi(0, "LspCxxHlGroupEnumConstant", { fg = "#ff9966" })
hi(0, "LspCxxHlGroupMemberVariable", { fg = "#ff9966" })
hi(0, "LspCxxHlGroupNamespace", { fg = "#57a5e5" })
hi(0, "LspCxxHlSkippedRegion", { fg = "#5b5e5a" })
hi(0, "LspCxxHlSkippedRegionBeginEnd", { fg = "#e75a7c" })
hi(0, "LspDiagnosticsDefaultError", { fg = "#e75a7c" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#aaaaff" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#70c2be" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#dbb671" })
hi(0, "LspDiagnosticsUnderlineError", { sp = "#e75a7c", undercurl = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = "#aaaaff", undercurl = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = "#57a5e5", undercurl = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = "#dbb671", undercurl = true })
hi(0, "LspDiagnosticsVirtualTextError", { bg = "#382b2c", fg = "#e75a7c" })
hi(0, "LspDiagnosticsVirtualTextHint", { bg = "#323339", fg = "#aaaaff" })
hi(0, "LspDiagnosticsVirtualTextInformation", { bg = "#2d3633", fg = "#70c2be" })
hi(0, "LspDiagnosticsVirtualTextWarning", { bg = "#37342b", fg = "#dbb671" })
hi(0, "LspInfoBorder", { link = "FloatBorder" })
hi(0, "LspReferenceRead", { bg = "#383b35" })
hi(0, "LspReferenceText", { bg = "#383b35" })
hi(0, "LspReferenceWrite", { bg = "#383b35" })
hi(0, "Macro", { fg = "#bfa6d9" })
hi(0, "MatchParen", { bg = "#5b5e5a", bold = true, fg = "#ff9966" })
hi(0, "MatchWord", { underline = true })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniIndentscopePrefix", { nocombine = true })
hi(0, "MiniIndentscopeSymbol", { link = "Comment" })
hi(0, "MiniJump", { fg = "#aaaaff", sp = "#aaaaff", underline = true })
hi(0, "MiniJump2dSpot", { bold = true, fg = "#e75a7c", nocombine = true })
hi(0, "MiniStarterCurrent", { nocombine = true })
hi(0, "MiniStarterFooter", { fg = "#833b3b", italic = true })
hi(0, "MiniStarterHeader", { fg = "#dbb671" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItem", { bg = "#252623", fg = "#f1e9d2" })
hi(0, "MiniStarterItemBullet", { fg = "#5b5e5a" })
hi(0, "MiniStarterItemPrefix", { fg = "#dbb671" })
hi(0, "MiniStarterQuery", { fg = "#70c2be" })
hi(0, "MiniStarterSection", { fg = "#838781" })
hi(0, "MiniStatuslineDevinfo", { bg = "#383b35", fg = "#f1e9d2" })
hi(0, "MiniStatuslineFileinfo", { bg = "#383b35", fg = "#f1e9d2" })
hi(0, "MiniStatuslineFilename", { bg = "#2f312c", fg = "#5b5e5a" })
hi(0, "MiniStatuslineInactive", { bg = "#252623", fg = "#5b5e5a" })
hi(0, "MiniStatuslineModeCommand", { bg = "#dbb671", bold = true, fg = "#252623" })
hi(0, "MiniStatuslineModeInsert", { bg = "#57a5e5", bold = true, fg = "#252623" })
hi(0, "MiniStatuslineModeNormal", { bg = "#8fb573", bold = true, fg = "#252623" })
hi(0, "MiniStatuslineModeOther", { bg = "#70c2be", bold = true, fg = "#252623" })
hi(0, "MiniStatuslineModeReplace", { bg = "#e75a7c", bold = true, fg = "#252623" })
hi(0, "MiniStatuslineModeVisual", { bg = "#aaaaff", bold = true, fg = "#252623" })
hi(0, "MiniSurround", { bg = "#ff9966", fg = "#252623" })
hi(0, "MiniTablineCurrent", { bold = true })
hi(0, "MiniTablineFill", { bg = "#2f312c", fg = "#5b5e5a" })
hi(0, "MiniTablineHidden", { bg = "#2f312c", fg = "#f1e9d2" })
hi(0, "MiniTablineModifiedCurrent", { bold = true, fg = "#ff9966", italic = true })
hi(0, "MiniTablineModifiedHidden", { bg = "#2f312c", fg = "#838781", italic = true })
hi(0, "MiniTablineModifiedVisible", { bg = "#252623", fg = "#dbb671", italic = true })
hi(0, "MiniTablineTabpagesection", { bg = "#e2c792", fg = "#252623" })
hi(0, "MiniTablineVisible", { bg = "#252623", fg = "#838781" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#e75a7c" })
hi(0, "MiniTestPass", { bold = true, fg = "#8fb573" })
hi(0, "MiniTrailspace", { bg = "#e75a7c" })
hi(0, "MoreMsg", { bold = true, fg = "#57a5e5" })
hi(0, "NavicIconsArray", { fg = "#dbb671" })
hi(0, "NavicIconsBoolean", { fg = "#ff9966" })
hi(0, "NavicIconsClass", { fg = "#dbb671" })
hi(0, "NavicIconsColor", { fg = "#8fb573" })
hi(0, "NavicIconsConstant", { fg = "#ff9966" })
hi(0, "NavicIconsConstructor", { fg = "#57a5e5" })
hi(0, "NavicIconsDefault", { fg = "#aaaaff" })
hi(0, "NavicIconsEnum", { fg = "#dbb671" })
hi(0, "NavicIconsEnumMember", { fg = "#ff9966" })
hi(0, "NavicIconsEvent", { fg = "#dbb671" })
hi(0, "NavicIconsField", { fg = "#70c2be" })
hi(0, "NavicIconsFile", { fg = "#8fb573" })
hi(0, "NavicIconsFolder", { fg = "#96c7ef" })
hi(0, "NavicIconsFunction", { fg = "#57a5e5" })
hi(0, "NavicIconsInterface", { fg = "#8fb573" })
hi(0, "NavicIconsKey", { fg = "#70c2be" })
hi(0, "NavicIconsKeyword", { fg = "#aaaaff" })
hi(0, "NavicIconsMethod", { fg = "#57a5e5" })
hi(0, "NavicIconsModule", { fg = "#96c7ef" })
hi(0, "NavicIconsNamespace", { fg = "#96c7ef" })
hi(0, "NavicIconsNull", { fg = "#5b5e5a" })
hi(0, "NavicIconsNumber", { fg = "#ff9966" })
hi(0, "NavicIconsObject", { fg = "#e75a7c" })
hi(0, "NavicIconsOperator", { fg = "#c5c2ee" })
hi(0, "NavicIconsPackage", { fg = "#dbb671" })
hi(0, "NavicIconsProperty", { fg = "#70c2be" })
hi(0, "NavicIconsReference", { fg = "#ff9966" })
hi(0, "NavicIconsSnippet", { fg = "#bfa6d9" })
hi(0, "NavicIconsString", { fg = "#8fb573" })
hi(0, "NavicIconsStruct", { fg = "#dbb671" })
hi(0, "NavicIconsText", { fg = "#838781" })
hi(0, "NavicIconsTypeParameter", { fg = "#f08080" })
hi(0, "NavicIconsUnit", { fg = "#dbb671" })
hi(0, "NavicIconsValue", { fg = "#ff9966" })
hi(0, "NavicIconsVariable", { fg = "#e75a7c" })
hi(0, "NavicSeparator", { fg = "#838781" })
hi(0, "NavicText", { fg = "#f1e9d2" })
hi(0, "NeoTreeEndOfBuffer", { bg = "#1c1e1b", fg = "#1c1e1b" })
hi(0, "NeoTreeFloatBorder", { link = "FloatBorder" })
hi(0, "NeoTreeFloatTitle", { link = "FloatTitle" })
hi(0, "NeoTreeGitAdded", { fg = "#8fb573" })
hi(0, "NeoTreeGitConflict", { bold = true, fg = "#e75a7c", italic = true })
hi(0, "NeoTreeGitDeleted", { fg = "#e75a7c" })
hi(0, "NeoTreeGitModified", { fg = "#dbb671" })
hi(0, "NeoTreeGitUntracked", { fg = "#e75a7c", italic = true })
hi(0, "NeoTreeIndentMarker", { fg = "#5b5e5a" })
hi(0, "NeoTreeNormal", { bg = "#1c1e1b", fg = "#f1e9d2" })
hi(0, "NeoTreeNormalNC", { bg = "#1c1e1b", fg = "#f1e9d2" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#ff9966" })
hi(0, "NeoTreeSymbolicLinkTarget", { fg = "#aaaaff" })
hi(0, "NeoTreeTitleBar", { bg = "#aaaaff", fg = "#252623" })
hi(0, "NeoTreeVertSplit", { bg = "#2f312c", fg = "#2f312c" })
hi(0, "NeoTreeWinSeparator", { bg = "#2f312c", fg = "#2f312c" })
hi(0, "NeotestAdapterName", { bold = true, fg = "#aaaaff" })
hi(0, "NeotestDir", { fg = "#70c2be" })
hi(0, "NeotestExpandMarker", { fg = "#5b5e5a" })
hi(0, "NeotestFailed", { fg = "#e75a7c" })
hi(0, "NeotestFile", { fg = "#70c2be" })
hi(0, "NeotestFocused", { bold = true, italic = true })
hi(0, "NeotestIndent", { fg = "#5b5e5a" })
hi(0, "NeotestMarked", { bold = true, fg = "#ff9966" })
hi(0, "NeotestNamespace", { fg = "#57a5e5" })
hi(0, "NeotestPassed", { fg = "#8fb573" })
hi(0, "NeotestRunning", { fg = "#dbb671" })
hi(0, "NeotestSkipped", { fg = "#838781" })
hi(0, "NeotestTarget", { fg = "#aaaaff" })
hi(0, "NeotestTest", { fg = "#f1e9d2" })
hi(0, "NeotestUnknown", { fg = "#838781" })
hi(0, "NeotestWinSelect", { bold = true, fg = "#70c2be" })
hi(0, "NoiceFormatProgressDone", { bg = "#e2c792", fg = "#252623" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = "#5b5e5a" })
hi(0, "Normal", { bg = "#252623", fg = "#f1e9d2" })
hi(0, "NormalFloat", { bg = "#252623", fg = "#f1e9d2" })
hi(0, "NormalNC", { bg = "#252623", fg = "#f1e9d2" })
hi(0, "NotifyBackground", { bg = "#252623" })
hi(0, "NotifyDEBUGBorder", { link = "Debug" })
hi(0, "NotifyDEBUGIcon", { link = "Debug" })
hi(0, "NotifyDEBUGTitle", { link = "Debug" })
hi(0, "NotifyERRORBorder", { link = "DiagnosticError" })
hi(0, "NotifyERRORIcon", { link = "DiagnosticError" })
hi(0, "NotifyERRORTitle", { link = "DiagnosticError" })
hi(0, "NotifyHINTBorder", { link = "DiagnosticHint" })
hi(0, "NotifyHINTIcon", { link = "DiagnosticHint" })
hi(0, "NotifyHINTTitle", { link = "DiagnosticHint" })
hi(0, "NotifyINFOBorder", { link = "DiagnosticInfo" })
hi(0, "NotifyINFOIcon", { link = "DiagnosticInfo" })
hi(0, "NotifyINFOTitle", { link = "DiagnosticInfo" })
hi(0, "NotifyTRACEBorder", { link = "Comment" })
hi(0, "NotifyTRACEIcon", { link = "Comment" })
hi(0, "NotifyTRACETitle", { link = "Comment" })
hi(0, "NotifyWARNBorder", { link = "DiagnosticWarn" })
hi(0, "NotifyWARNIcon", { link = "DiagnosticWarn" })
hi(0, "NotifyWARNTitle", { link = "DiagnosticWarn" })
hi(0, "NvimTreeFolderName", { fg = "#57a5e5" })
hi(0, "NvimTreeGitDeleted", { fg = "#e75a7c" })
hi(0, "NvimTreeGitDirty", { fg = "#dbb671" })
hi(0, "NvimTreeGitNew", { fg = "#8fb573" })
hi(0, "NvimTreeImageFile", { fg = "#79428a" })
hi(0, "NvimTreeIndentMarker", { fg = "#f1e9d2" })
hi(0, "NvimTreeNormal", { bg = "#252623", fg = "#f1e9d2" })
hi(0, "NvimTreeOpenedFile", { bold = true, fg = "#f08080", italic = true })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#ff9966" })
hi(0, "NvimTreeSignColumn", { nocombine = true })
hi(0, "NvimTreeSpecialFile", { fg = "#dbb671", underline = true })
hi(0, "NvimTreeVertSplit", { bg = "#1c1e1b", fg = "#1c1e1b" })
hi(0, "Operator", { fg = "#c5c2ee" })
hi(0, "Pmenu", { bg = "#2f312c", fg = "#f1e9d2" })
hi(0, "PmenuSbar", { bg = "#2f312c" })
hi(0, "PmenuSel", { bg = "#68aee8", fg = "#252623" })
hi(0, "PmenuThumb", { bg = "#5b5e5a" })
hi(0, "PreProc", { fg = "#aaaaff" })
hi(0, "Question", { fg = "#dbb671" })
hi(0, "QuickFixLine", { fg = "#57a5e5", underline = true })
hi(0, "RainbowDelimiterBlue", { link = "rainbowcol3" })
hi(0, "RainbowDelimiterCyan", { link = "rainbowcol7" })
hi(0, "RainbowDelimiterGreen", { link = "rainbowcol5" })
hi(0, "RainbowDelimiterOrange", { link = "rainbowcol4" })
hi(0, "RainbowDelimiterRed", { link = "rainbowcol1" })
hi(0, "RainbowDelimiterViolet", { link = "rainbowcol6" })
hi(0, "RainbowDelimiterYellow", { link = "rainbowcol2" })
hi(0, "Repeat", { link = "Keyword" })
hi(0, "Search", { bg = "#e2c792", fg = "#252623" })
hi(0, "SignColumn", { fg = "#f1e9d2" })
hi(0, "Special", { fg = "#e75a7c" })
hi(0, "SpecialComment", { link = "Comment" })
hi(0, "SpecialKey", { link = "NonText" })
hi(0, "SpellBad", { sp = "#e75a7c", undercurl = true })
hi(0, "SpellCap", { sp = "#dbb671", undercurl = true })
hi(0, "SpellLocal", { sp = "#57a5e5", undercurl = true })
hi(0, "SpellRare", { sp = "#aaaaff", undercurl = true })
hi(0, "Statement", { fg = "#aaaaff" })
hi(0, "StorageClass", { fg = "#dbb671", italic = true })
hi(0, "Strike", { strikethrough = true })
hi(0, "String", { fg = "#8fb573" })
hi(0, "Substitute", { bg = "#8fb573", fg = "#252623" })
hi(0, "TSRainbowBlue", { link = "rainbowcol3" })
hi(0, "TSRainbowCyan", { link = "rainbowcol7" })
hi(0, "TSRainbowGreen", { link = "rainbowcol5" })
hi(0, "TSRainbowOrange", { link = "rainbowcol4" })
hi(0, "TSRainbowRed", { link = "rainbowcol1" })
hi(0, "TSRainbowViolet", { link = "rainbowcol6" })
hi(0, "TSRainbowYellow", { link = "rainbowcol2" })
hi(0, "TabLine", { bg = "#2f312c", fg = "#f1e9d2" })
hi(0, "TabLineFill", { bg = "#2f312c", fg = "#5b5e5a" })
hi(0, "TabLineSel", { bg = "#f1e9d2", fg = "#252623" })
hi(0, "Tag", { fg = "#57a5e5" })
hi(0, "TelescopeBorder", { fg = "#e75a7c" })
hi(0, "TelescopeMatching", { bold = true, fg = "#ff9966" })
hi(0, "TelescopePreviewBorder", { fg = "#aaaaff" })
hi(0, "TelescopePromptBorder", { fg = "#aaaaff" })
hi(0, "TelescopePromptPrefix", { fg = "#8fb573" })
hi(0, "TelescopeResultsBorder", { fg = "#aaaaff" })
hi(0, "TelescopeSelection", { bg = "#383b35" })
hi(0, "TelescopeSelectionCaret", { bg = "#383b35", bold = true, fg = "#ff9966" })
hi(0, "Terminal", { bg = "#252623", fg = "#f1e9d2" })
hi(0, "Title", { bold = true, fg = "#70c2be" })
hi(0, "Todo", { bg = "#aaaaff", bold = true, fg = "#111210" })
hi(0, "ToolbarButton", { bg = "#68aee8", fg = "#252623" })
hi(0, "ToolbarLine", { fg = "#f1e9d2" })
hi(0, "TreesitterContext", { bg = "#2f312c" })
hi(0, "Type", { fg = "#dbb671" })
hi(0, "VertSplit", { fg = "#3a3d37" })
hi(0, "Visual", { bg = "#3a3d37" })
hi(0, "VisualNOS", { bg = "#383b35", underline = true })
hi(0, "WarningMsg", { bold = true, fg = "#dbb671" })
hi(0, "WhichKey", { fg = "#e75a7c" })
hi(0, "WhichKeyDesc", { fg = "#57a5e5" })
hi(0, "WhichKeyGroup", { fg = "#ff9966" })
hi(0, "WhichKeySeparator", { fg = "#8fb573" })
hi(0, "WildMenu", { bg = "#57a5e5", fg = "#252623" })
hi(0, "WinBar", { fg = "#f08080" })
hi(0, "WinBarNC", { link = "WinBar" })
hi(0, "WinSeparator", { fg = "#3a3d37" })
hi(0, "cDefine", { fg = "#70c2be" })
hi(0, "cInclude", { fg = "#57a5e5" })
hi(0, "cStorageClass", { fg = "#aaaaff" })
hi(0, "cTypedef", { fg = "#aaaaff" })
hi(0, "cppStatement", { bold = true, fg = "#aaaaff" })
hi(0, "debugBreakpoint", { bg = "#e75a7c", fg = "#252623" })
hi(0, "debugPC", { bg = "#8fb573", fg = "#252623" })
hi(0, "lCursor", { link = "Cursor" })
hi(0, "markdownBlockquote", { link = "Special" })
hi(0, "markdownBold", { bold = true })
hi(0, "markdownBoldDelimiter", { link = "Delimiter" })
hi(0, "markdownCode", { fg = "#8fb573" })
hi(0, "markdownCodeBlock", { fg = "#8fb573" })
hi(0, "markdownCodeDelimiter", { fg = "#dbb671" })
hi(0, "markdownH1", { bold = true, fg = "#e75a7c" })
hi(0, "markdownH2", { bold = true, fg = "#dbb671" })
hi(0, "markdownH3", { bold = true, fg = "#8fb573" })
hi(0, "markdownH4", { bold = true, fg = "#70c2be" })
hi(0, "markdownH5", { bold = true, fg = "#57a5e5" })
hi(0, "markdownH6", { bold = true, fg = "#aaaaff" })
hi(0, "markdownHeadingDelimiter", { fg = "#ff9966" })
hi(0, "markdownHeadingRule", { fg = "#ff9966" })
hi(0, "markdownId", { fg = "#dbb671" })
hi(0, "markdownIdDeclaration", { fg = "#e75a7c" })
hi(0, "markdownItalic", { italic = true })
hi(0, "markdownItalicDelimiter", { fg = "#838781", italic = true })
hi(0, "markdownLinkDelimiter", { link = "Delimiter" })
hi(0, "markdownLinkText", { fg = "#57a5e5" })
hi(0, "markdownLinkTextDelimiter", { link = "Delimiter" })
hi(0, "markdownListMarker", { fg = "#e75a7c" })
hi(0, "markdownOrderedListMarker", { fg = "#e75a7c" })
hi(0, "markdownRule", { fg = "#aaaaff" })
hi(0, "markdownUrl", { fg = "#70c2be", underline = true })
hi(0, "markdownUrlDelimiter", { link = "Delimiter" })
hi(0, "markdownUrlTitleDelimiter", { fg = "#8fb573" })
hi(0, "phpBoolean", { fg = "#70c2be" })
hi(0, "phpFCKeyword", { fg = "#aaaaff" })
hi(0, "phpFunctions", { fg = "#f1e9d2" })
hi(0, "phpHereDoc", { fg = "#8fb573" })
hi(0, "phpIdentifier", { fg = "#ff9966" })
hi(0, "phpMemberSelector", { fg = "#f1e9d2" })
hi(0, "phpMethods", { fg = "#70c2be" })
hi(0, "phpNowDoc", { fg = "#8fb573" })
hi(0, "phpRegion", { fg = "#57a5e5" })
hi(0, "phpSCKeyword", { fg = "#aaaaff" })
hi(0, "phpStructure", { fg = "#aaaaff" })
hi(0, "phpVarSelector", { fg = "#ff9966" })
hi(0, "rainbowcol1", { fg = "#e75a7c" })
hi(0, "rainbowcol2", { fg = "#dbb671" })
hi(0, "rainbowcol3", { fg = "#57a5e5" })
hi(0, "rainbowcol4", { fg = "#ff9966" })
hi(0, "rainbowcol5", { fg = "#b4c997" })
hi(0, "rainbowcol6", { fg = "#aaaaff" })
hi(0, "rainbowcol7", { fg = "#70c2be" })
hi(0, "scalaInterpolation", { fg = "#aaaaff" })
hi(0, "scalaInterpolationBoundary", { fg = "#aaaaff" })
hi(0, "scalaKeywordModifier", { fg = "#e75a7c" })
hi(0, "scalaNameDefinition", { fg = "#f1e9d2" })
hi(0, "scalaOperator", { fg = "#e75a7c" })
hi(0, "scalaTypeOperator", { fg = "#e75a7c" })
hi(0, "texCmd", { fg = "#aaaaff" })
hi(0, "texCmdEnv", { fg = "#70c2be" })
hi(0, "texCmdPackage", { fg = "#57a5e5" })
hi(0, "texCmdPart", { fg = "#57a5e5" })
hi(0, "texEnvArgName", { fg = "#dbb671" })
hi(0, "texMathDelim", { fg = "#aaaaff" })
hi(0, "texMathDelimZone", { fg = "#838781" })
hi(0, "texMathOper", { fg = "#e75a7c" })
hi(0, "texMathZoneX", { fg = "#ff9966" })
hi(0, "texMathZoneXX", { fg = "#ff9966" })
hi(0, "texPgfType", { fg = "#dbb671" })
hi(0, "vimCommentTitle", { fg = "#dbb671", italic = true })
hi(0, "vimMap", { fg = "#aaaaff" })
hi(0, "vimMapLhs", { fg = "#f1e9d2" })
hi(0, "vimMapModKey", { fg = "#ff9966" })
hi(0, "vimMapRhs", { fg = "#57a5e5" })
hi(0, "vimNotation", { fg = "#e75a7c" })
hi(0, "vimOption", { fg = "#e75a7c" })
hi(0, "vimSetEqual", { fg = "#dbb671" })
hi(0, "vimVar", { fg = "#f1e9d2" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#111210"
g.terminal_color_1 = "#e75a7c"
g.terminal_color_2 = "#8fb573"
g.terminal_color_3 = "#dbb671"
g.terminal_color_4 = "#57a5e5"
g.terminal_color_5 = "#aaaaff"
g.terminal_color_6 = "#70c2be"
g.terminal_color_7 = "#f1e9d2"
g.terminal_color_8 = "#5b5e5a"
g.terminal_color_9 = "#e75a7c"
g.terminal_color_10 = "#8fb573"
g.terminal_color_11 = "#dbb671"
g.terminal_color_12 = "#57a5e5"
g.terminal_color_13 = "#aaaaff"
g.terminal_color_14 = "#70c2be"
g.terminal_color_15 = "#f1e9d2"
