-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
	vim.cmd("highlight clear")
end
vim.g.colors_name = "catppuccin-material"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@annotation", { link = "TSAnnotation" })
hi(0, "@attribute", { link = "TSAttribute" })
hi(0, "@boolean", { link = "TSBoolean" })
hi(0, "@character", { link = "TSCharacter" })
hi(0, "@character.special", { link = "TSCharacterSpecial" })
hi(0, "@comment", { link = "TSComment" })
hi(0, "@comment.error", { bg = "#ea6962", fg = "#1d2021" })
hi(0, "@comment.hint", { bg = "#7daea3", fg = "#1d2021" })
hi(0, "@comment.note", { bg = "#7daea3", fg = "#1d2021" })
hi(0, "@comment.todo", { bg = "#ea6962", fg = "#1d2021" })
hi(0, "@comment.warning", { bg = "#d8a657", fg = "#1d2021" })
hi(0, "@conceal", { link = "Grey" })
hi(0, "@conditional", { link = "TSConditional" })
hi(0, "@constant", { link = "TSConstant" })
hi(0, "@constant.builtin", { fg = "#d3869b" })
hi(0, "@constant.java", { fg = "#89b482" })
hi(0, "@constant.macro", { link = "TSConstMacro" })
hi(0, "@constructor", { fg = "#a9b665" })
hi(0, "@constructor.lua", { fg = "#ea6962" })
hi(0, "@constructor.tsx", { fg = "#7daea3" })
hi(0, "@constructor.typescript", { fg = "#7daea3" })
hi(0, "@debug", { link = "TSDebug" })
hi(0, "@define", { link = "TSDefine" })
hi(0, "@diff.delta", { link = "diffChanged" })
hi(0, "@diff.minus", { link = "diffRemoved" })
hi(0, "@diff.plus", { link = "diffAdded" })
hi(0, "@error", { link = "TSError" })
hi(0, "@exception", { link = "TSException" })
hi(0, "@field", { fg = "#7daea3" })
hi(0, "@float", { link = "TSFloat" })
hi(0, "@function", { link = "TSFunction" })
hi(0, "@function.builtin", { fg = "#a9b665" })
hi(0, "@function.builtin.bash", { fg = "#ea6962", italic = true })
hi(0, "@function.call", { link = "TSFunctionCall" })
hi(0, "@function.macro", { fg = "#a9b665" })
hi(0, "@function.method", { link = "Function" })
hi(0, "@function.method.call", { link = "Function" })
hi(0, "@function.method.call.php", { link = "Function" })
hi(0, "@function.method.php", { link = "Function" })
hi(0, "@include", { link = "TSInclude" })
hi(0, "@keyword", { link = "TSKeyword" })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.directive", { link = "PreProc" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.export", { fg = "#89b482" })
hi(0, "@keyword.function", { fg = "#ea6962" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.operator", { fg = "#e78a4e" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.return", { fg = "#ea6962" })
hi(0, "@keyword.storage", { link = "StorageClass" })
hi(0, "@label", { link = "TSLabel" })
hi(0, "@label.json", { fg = "#7daea3" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.class", { link = "TSType" })
hi(0, "@lsp.type.comment", { link = "TSComment" })
hi(0, "@lsp.type.decorator", { link = "TSFunction" })
hi(0, "@lsp.type.enum", { link = "TSType" })
hi(0, "@lsp.type.enumMember", { link = "TSProperty" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.events", { link = "TSLabel" })
hi(0, "@lsp.type.formatSpecifier", { link = "@punctuation.special" })
hi(0, "@lsp.type.function", { link = "TSFunction" })
hi(0, "@lsp.type.interface", { bold = true, fg = "#d8a657" })
hi(0, "@lsp.type.keyword", { link = "TSKeyword" })
hi(0, "@lsp.type.macro", { link = "TSConstMacro" })
hi(0, "@lsp.type.method", { link = "TSMethod" })
hi(0, "@lsp.type.modifier", { link = "TSTypeQualifier" })
hi(0, "@lsp.type.namespace", { link = "TSNamespace" })
hi(0, "@lsp.type.number", { link = "TSNumber" })
hi(0, "@lsp.type.operator", { link = "TSOperator" })
hi(0, "@lsp.type.parameter", { link = "TSParameter" })
hi(0, "@lsp.type.property", { link = "TSProperty" })
hi(0, "@lsp.type.regexp", { link = "TSStringRegex" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.string", { link = "TSString" })
hi(0, "@lsp.type.struct", { link = "TSType" })
hi(0, "@lsp.type.type", { link = "TSType" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.typeParameter", { link = "TSTypeDefinition" })
hi(0, "@lsp.type.unresolvedReference", { link = "@error" })
hi(0, "@lsp.type.variable", { link = "TSVariable" })
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@markup", { fg = "#ebdbb2" })
hi(0, "@markup.environment", { fg = "#d3869b" })
hi(0, "@markup.environment.name", { fg = "#7daea3" })
hi(0, "@markup.heading", { bold = true, fg = "#7daea3" })
hi(0, "@markup.heading.1.markdown", { link = "rainbow1" })
hi(0, "@markup.heading.2.markdown", { link = "rainbow2" })
hi(0, "@markup.heading.3.markdown", { link = "rainbow3" })
hi(0, "@markup.heading.4.markdown", { link = "rainbow4" })
hi(0, "@markup.heading.5.markdown", { link = "rainbow5" })
hi(0, "@markup.heading.6.markdown", { link = "rainbow6" })
hi(0, "@markup.italic", { fg = "#ea6962", italic = true })
hi(0, "@markup.link", { link = "Tag" })
hi(0, "@markup.link.url", { fg = "#ea6962", italic = true, underline = true })
hi(0, "@markup.list", { link = "Special" })
hi(0, "@markup.list.checked", { fg = "#a9b665" })
hi(0, "@markup.list.unchecked", { fg = "#928374" })
hi(0, "@markup.math", { fg = "#7daea3" })
hi(0, "@markup.raw", { fg = "#89b482" })
hi(0, "@markup.strikethrough", { fg = "#ebdbb2", strikethrough = true })
hi(0, "@markup.strong", { bold = true, fg = "#ea6962" })
hi(0, "@markup.underline", { link = "Underline" })
hi(0, "@math", { link = "TSMath" })
hi(0, "@method", { link = "TSMethod" })
hi(0, "@method.call", { link = "TSMethodCall" })
hi(0, "@method.call.php", { link = "Function" })
hi(0, "@method.php", { link = "Function" })
hi(0, "@module", { fg = "#7daea3", italic = true })
hi(0, "@namespace", { fg = "#d8a657" })
hi(0, "@none", { link = "TSNone" })
hi(0, "@number", { link = "TSNumber" })
hi(0, "@number.css", { fg = "#e78a4e" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@operator", { link = "TSOperator" })
hi(0, "@parameter", { fg = "#ebdbb2" })
hi(0, "@parameter.reference", { link = "TSParameterReference" })
hi(0, "@preproc", { link = "TSPreProc" })
hi(0, "@property", { fg = "#7daea3" })
hi(0, "@property.class.css", { fg = "#d8a657" })
hi(0, "@property.cpp", { fg = "#ebdbb2" })
hi(0, "@property.css", { fg = "#7daea3" })
hi(0, "@property.id.css", { fg = "#7daea3" })
hi(0, "@property.toml", { fg = "#7daea3" })
hi(0, "@property.typescript", { fg = "#7daea3" })
hi(0, "@punctuation.bracket", { fg = "#ebdbb2" })
hi(0, "@punctuation.delimiter", { link = "TSPunctDelimiter" })
hi(0, "@punctuation.special", { link = "TSPunctSpecial" })
hi(0, "@repeat", { link = "TSRepeat" })
hi(0, "@storageclass", { link = "TSStorageClass" })
hi(0, "@storageclass.lifetime", { link = "TSStorageClassLifetime" })
hi(0, "@strike", { link = "TSStrike" })
hi(0, "@string", { link = "TSString" })
hi(0, "@string.escape", { fg = "#a9b665" })
hi(0, "@string.plain.css", { fg = "#e78a4e" })
hi(0, "@string.regex", { fg = "#a9b665" })
hi(0, "@string.regexp", { fg = "#e78a4e" })
hi(0, "@string.special", { link = "TSStringSpecial" })
hi(0, "@string.special.symbol", { fg = "#ea6962" })
hi(0, "@string.special.symbol.ruby", { fg = "#ea6962" })
hi(0, "@string.special.url", { fg = "#ea6962", italic = true, underline = true })
hi(0, "@symbol", { fg = "#ebdbb2" })
hi(0, "@symbol.ruby", { fg = "#ea6962" })
hi(0, "@tag", { fg = "#e78a4e" })
hi(0, "@tag.attribute", { fg = "#a9b665" })
hi(0, "@tag.attribute.tsx", { fg = "#d3869b", italic = true })
hi(0, "@tag.delimiter", { fg = "#a9b665" })
hi(0, "@text", { fg = "#a9b665" })
hi(0, "@text.danger", {})
hi(0, "@text.diff.add", { link = "diffAdded" })
hi(0, "@text.diff.delete", { link = "diffRemoved" })
hi(0, "@text.emphasis", {})
hi(0, "@text.environment", { fg = "#89b482" })
hi(0, "@text.environment.name", { bold = true, fg = "#d8a657" })
hi(0, "@text.literal", { fg = "#a9b665" })
hi(0, "@text.math", { fg = "#7daea3" })
hi(0, "@text.note", {})
hi(0, "@text.reference", { link = "TSTextReference" })
hi(0, "@text.strike", {})
hi(0, "@text.strong", {})
hi(0, "@text.title", { bold = true, fg = "#e78a4e" })
hi(0, "@text.title.1.markdown", { link = "rainbow1" })
hi(0, "@text.title.2.markdown", { link = "rainbow2" })
hi(0, "@text.title.3.markdown", { link = "rainbow3" })
hi(0, "@text.title.4.markdown", { link = "rainbow4" })
hi(0, "@text.title.5.markdown", { link = "rainbow5" })
hi(0, "@text.title.6.markdown", { link = "rainbow6" })
hi(0, "@text.todo", { bg = "#ea6962", bold = true, fg = "#1d2021" })
hi(0, "@text.todo.checked", {})
hi(0, "@text.todo.unchecked", {})
hi(0, "@text.underline", { link = "TSUnderline" })
hi(0, "@text.uri", { link = "TSURI" })
hi(0, "@text.warning", {})
hi(0, "@todo", { link = "TSTodo" })
hi(0, "@type", { link = "TSType" })
hi(0, "@type.builtin", { bold = true, fg = "#d8a657" })
hi(0, "@type.builtin.c", { fg = "#d8a657" })
hi(0, "@type.builtin.cpp", { fg = "#d8a657" })
hi(0, "@type.css", { fg = "#7daea3" })
hi(0, "@type.definition", { link = "TSTypeDefinition" })
hi(0, "@type.qualifier", { link = "TSTypeQualifier" })
hi(0, "@type.tag.css", { fg = "#d3869b" })
hi(0, "@uri", { link = "TSURI" })
hi(0, "@variable", { fg = "#ebdbb2" })
hi(0, "@variable.builtin", { fg = "#d3869b" })
hi(0, "@variable.member", { fg = "#7daea3" })
hi(0, "@variable.parameter", { fg = "#ea6962" })
hi(0, "AlphaButtons", { fg = "#7daea3" })
hi(0, "AlphaFooter", { fg = "#d8a657", italic = true })
hi(0, "AlphaHeader", { fg = "#7daea3" })
hi(0, "AlphaHeaderLabel", { fg = "#e78a4e" })
hi(0, "AlphaShortcut", { fg = "#a9b665" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#d3869b" })
hi(0, "Character", { fg = "#89b482" })
hi(0, "CmpItemAbbr", { fg = "#a89984" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#595959", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#595959" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#ebdbb2" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#ebdbb2" })
hi(0, "CmpItemKind", { fg = "#7daea3" })
hi(0, "CmpItemKindClass", { fg = "#d8a657" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { fg = "#ea6962" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { fg = "#e78a4e" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { fg = "#7daea3" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { fg = "#89b482" })
hi(0, "CmpItemKindDefault", { fg = "#d8a657" })
hi(0, "CmpItemKindEnum", { fg = "#a9b665" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { fg = "#ea6962" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { fg = "#7daea3" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { fg = "#a9b665" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { fg = "#7daea3" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { fg = "#7daea3" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { fg = "#7daea3" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { fg = "#d8a657" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { fg = "#ea6962" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { fg = "#7daea3" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { fg = "#7daea3" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { fg = "#7daea3" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { fg = "#a9b665" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { fg = "#ea6962" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#d3869b" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { fg = "#7daea3" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { fg = "#89b482" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { fg = "#7daea3" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { fg = "#a9b665" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { fg = "#e78a4e" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#ea6962" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#4d4d4d" })
hi(0, "ColorColumn", { bg = "#292929" })
hi(0, "Comment", { fg = "#595959", italic = true })
hi(0, "Conceal", { fg = "#928374" })
hi(0, "Conditional", { fg = "#ea6962", italic = true })
hi(0, "Constant", { fg = "#e78a4e" })
hi(0, "CurSearch", { bg = "#ea6962", fg = "#191b1c" })
hi(0, "Cursor", { bg = "#ebdbb2", fg = "#1d2021" })
hi(0, "CursorColumn", { bg = "#191b1c" })
hi(0, "CursorIM", { bg = "#ebdbb2", fg = "#1d2021" })
hi(0, "CursorLine", { bg = "#252626" })
hi(0, "CursorLineNr", { fg = "#ebdbb2" })
hi(0, "DapBreakpoint", { fg = "#ea6962" })
hi(0, "DapBreakpointCondition", { fg = "#d8a657" })
hi(0, "DapBreakpointRejected", { fg = "#d3869b" })
hi(0, "DapLogPoint", { fg = "#89b482" })
hi(0, "DapStopped", { fg = "#ea6962" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#a9b665" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#4d4d4d" })
hi(0, "DapUIBreakpointsInfo", { fg = "#a9b665" })
hi(0, "DapUIBreakpointsPath", { fg = "#89b482" })
hi(0, "DapUIDecoration", { fg = "#89b482" })
hi(0, "DapUIFloatBorder", { fg = "#89b482" })
hi(0, "DapUILineNumber", { fg = "#89b482" })
hi(0, "DapUIModifiedValue", { fg = "#e78a4e" })
hi(0, "DapUIPlayPause", { fg = "#a9b665" })
hi(0, "DapUIPlayPauseNC", { fg = "#a9b665" })
hi(0, "DapUIRestart", { fg = "#a9b665" })
hi(0, "DapUIRestartNC", { fg = "#a9b665" })
hi(0, "DapUIScope", { fg = "#89b482" })
hi(0, "DapUISource", { fg = "#7daea3" })
hi(0, "DapUIStepBack", { fg = "#7daea3" })
hi(0, "DapUIStepBackNC", { fg = "#7daea3" })
hi(0, "DapUIStepInto", { fg = "#7daea3" })
hi(0, "DapUIStepIntoNC", { fg = "#7daea3" })
hi(0, "DapUIStepOut", { fg = "#7daea3" })
hi(0, "DapUIStepOutNC", { fg = "#7daea3" })
hi(0, "DapUIStepOver", { fg = "#7daea3" })
hi(0, "DapUIStepOverNC", { fg = "#7daea3" })
hi(0, "DapUIStop", { fg = "#ea6962" })
hi(0, "DapUIStopNC", { fg = "#ea6962" })
hi(0, "DapUIStoppedThread", { fg = "#89b482" })
hi(0, "DapUIThread", { fg = "#a9b665" })
hi(0, "DapUIType", { fg = "#d3869b" })
hi(0, "DapUIUnavailable", { fg = "#404040" })
hi(0, "DapUIUnavailableNC", { fg = "#404040" })
hi(0, "DapUIValue", { fg = "#89b482" })
hi(0, "DapUIVariable", { fg = "#ebdbb2" })
hi(0, "DapUIWatchesEmpty", { fg = "#ea6962" })
hi(0, "DapUIWatchesError", { fg = "#ea6962" })
hi(0, "DapUIWatchesValue", { fg = "#a9b665" })
hi(0, "DapUIWinSelect", { fg = "#e78a4e" })
hi(0, "DashboardCenter", { fg = "#a9b665" })
hi(0, "DashboardDesc", { fg = "#7daea3" })
hi(0, "DashboardFiles", { fg = "#7daea3" })
hi(0, "DashboardFooter", { fg = "#d8a657", italic = true })
hi(0, "DashboardHeader", { fg = "#7daea3" })
hi(0, "DashboardIcon", { bold = true, fg = "#d3869b" })
hi(0, "DashboardKey", { fg = "#e78a4e" })
hi(0, "DashboardMruTitle", { fg = "#89b482" })
hi(0, "DashboardProjectTitle", { fg = "#89b482" })
hi(0, "DashboardShortCut", { fg = "#d3869b" })
hi(0, "Define", { fg = "#d3869b" })
hi(0, "Delimiter", { fg = "#a89984" })
hi(0, "DiagnosticError", { fg = "#ea6962", italic = true })
hi(0, "DiagnosticFloatingError", { fg = "#ea6962" })
hi(0, "DiagnosticFloatingHint", { fg = "#89b482" })
hi(0, "DiagnosticFloatingInfo", { fg = "#89b482" })
hi(0, "DiagnosticFloatingWarn", { fg = "#d8a657" })
hi(0, "DiagnosticHint", { fg = "#89b482", italic = true })
hi(0, "DiagnosticInfo", { fg = "#89b482", italic = true })
hi(0, "DiagnosticSignError", { fg = "#ea6962" })
hi(0, "DiagnosticSignHint", { fg = "#89b482" })
hi(0, "DiagnosticSignInfo", { fg = "#89b482" })
hi(0, "DiagnosticSignWarn", { fg = "#d8a657" })
hi(0, "DiagnosticUnderlineError", { sp = "#ea6962", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#89b482", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#89b482", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#d8a657", underline = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#302727", fg = "#ea6962", italic = true })
hi(0, "DiagnosticVirtualTextHint", { bg = "#272e2a", fg = "#89b482", italic = true })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#272e2a", fg = "#89b482", italic = true })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#2f2d26", fg = "#d8a657", italic = true })
hi(0, "DiagnosticWarn", { fg = "#d8a657", italic = true })
hi(0, "DiffAdd", { bg = "#363b2d" })
hi(0, "DiffChange", { bg = "#242a2a" })
hi(0, "DiffDelete", { bg = "#422d2d" })
hi(0, "DiffText", { bg = "#3a4b48" })
hi(0, "Directory", { fg = "#7daea3" })
hi(0, "DressingSelectIdx", { link = "Special" })
hi(0, "DropBarIconUISeparator", { fg = "#928374" })
hi(0, "DropBarKindArray", { fg = "#ebdbb2" })
hi(0, "DropBarKindBoolean", { fg = "#ebdbb2" })
hi(0, "DropBarKindBreakStatement", { fg = "#ebdbb2" })
hi(0, "DropBarKindCall", { fg = "#ebdbb2" })
hi(0, "DropBarKindCaseStatement", { fg = "#ebdbb2" })
hi(0, "DropBarKindClass", { fg = "#ebdbb2" })
hi(0, "DropBarKindConstant", { fg = "#ebdbb2" })
hi(0, "DropBarKindConstructor", { fg = "#ebdbb2" })
hi(0, "DropBarKindContinueStatement", { fg = "#ebdbb2" })
hi(0, "DropBarKindDeclaration", { fg = "#ebdbb2" })
hi(0, "DropBarKindDelete", { fg = "#ebdbb2" })
hi(0, "DropBarKindDoStatement", { fg = "#ebdbb2" })
hi(0, "DropBarKindElseStatement", { fg = "#ebdbb2" })
hi(0, "DropBarKindEnum", { fg = "#ebdbb2" })
hi(0, "DropBarKindEnumMember", { fg = "#ebdbb2" })
hi(0, "DropBarKindEvent", { fg = "#ebdbb2" })
hi(0, "DropBarKindField", { fg = "#ebdbb2" })
hi(0, "DropBarKindFile", { fg = "#ebdbb2" })
hi(0, "DropBarKindFolder", { fg = "#ebdbb2" })
hi(0, "DropBarKindForStatement", { fg = "#ebdbb2" })
hi(0, "DropBarKindFunction", { fg = "#ebdbb2" })
hi(0, "DropBarKindIdentifier", { fg = "#ebdbb2" })
hi(0, "DropBarKindIfStatement", { fg = "#ebdbb2" })
hi(0, "DropBarKindInterface", { fg = "#ebdbb2" })
hi(0, "DropBarKindKeyword", { fg = "#ebdbb2" })
hi(0, "DropBarKindList", { fg = "#ebdbb2" })
hi(0, "DropBarKindMacro", { fg = "#ebdbb2" })
hi(0, "DropBarKindMarkdownH1", { fg = "#ebdbb2" })
hi(0, "DropBarKindMarkdownH2", { fg = "#ebdbb2" })
hi(0, "DropBarKindMarkdownH3", { fg = "#ebdbb2" })
hi(0, "DropBarKindMarkdownH4", { fg = "#ebdbb2" })
hi(0, "DropBarKindMarkdownH5", { fg = "#ebdbb2" })
hi(0, "DropBarKindMarkdownH6", { fg = "#ebdbb2" })
hi(0, "DropBarKindMethod", { fg = "#ebdbb2" })
hi(0, "DropBarKindModule", { fg = "#ebdbb2" })
hi(0, "DropBarKindNamespace", { fg = "#ebdbb2" })
hi(0, "DropBarKindNull", { fg = "#ebdbb2" })
hi(0, "DropBarKindNumber", { fg = "#ebdbb2" })
hi(0, "DropBarKindObject", { fg = "#ebdbb2" })
hi(0, "DropBarKindOperator", { fg = "#ebdbb2" })
hi(0, "DropBarKindPackage", { fg = "#ebdbb2" })
hi(0, "DropBarKindProperty", { fg = "#ebdbb2" })
hi(0, "DropBarKindReference", { fg = "#ebdbb2" })
hi(0, "DropBarKindRepeat", { fg = "#ebdbb2" })
hi(0, "DropBarKindScope", { fg = "#ebdbb2" })
hi(0, "DropBarKindSpecifier", { fg = "#ebdbb2" })
hi(0, "DropBarKindStatement", { fg = "#ebdbb2" })
hi(0, "DropBarKindString", { fg = "#ebdbb2" })
hi(0, "DropBarKindStruct", { fg = "#ebdbb2" })
hi(0, "DropBarKindSwitchStatement", { fg = "#ebdbb2" })
hi(0, "DropBarKindType", { fg = "#ebdbb2" })
hi(0, "DropBarKindTypeParameter", { fg = "#ebdbb2" })
hi(0, "DropBarKindUnit", { fg = "#ebdbb2" })
hi(0, "DropBarKindValue", { fg = "#ebdbb2" })
hi(0, "DropBarKindVariable", { fg = "#ebdbb2" })
hi(0, "DropBarKindWhileStatement", { fg = "#ebdbb2" })
hi(0, "DropBarMenuHoverEntry", { link = "Visual" })
hi(0, "DropBarMenuHoverIcon", { reverse = true })
hi(0, "DropBarMenuHoverSymbol", { bold = true })
hi(0, "EndOfBuffer", { fg = "#1d2021" })
hi(0, "Error", { fg = "#ea6962" })
hi(0, "ErrorMsg", { bold = true, fg = "#ea6962", italic = true })
hi(0, "Exception", { fg = "#ea6962" })
hi(0, "FidgetTitle", { fg = "#e78a4e" })
hi(0, "FlashBackdrop", { fg = "#595959" })
hi(0, "FlashCurrent", { bg = "#1d2021", fg = "#e78a4e" })
hi(0, "FlashLabel", { bg = "#1d2021", bold = true, fg = "#a9b665" })
hi(0, "FlashMatch", { bg = "#1d2021", fg = "#7daea3" })
hi(0, "FlashPrompt", { link = "NormalFloat" })
hi(0, "Float", { fg = "#d3869b" })
hi(0, "FloatBorder", { bg = "#1d2021", fg = "#292929" })
hi(0, "FloatTitle", { fg = "#bdae93" })
hi(0, "FoldColumn", { fg = "#595959" })
hi(0, "Folded", { bg = "#404040", fg = "#7daea3" })
hi(0, "Function", { bold = true, fg = "#a9b665" })
hi(0, "FzfLuaBufFlagAlt", { fg = "#98f5ff" })
hi(0, "FzfLuaBufFlagCur", { fg = "#ff4040" })
hi(0, "FzfLuaBufLineNr", { fg = "#00fa9a" })
hi(0, "FzfLuaBufName", { fg = "#ffbbff" })
hi(0, "FzfLuaBufNr", { fg = "#ffebcd" })
hi(0, "FzfLuaHeaderBind", { fg = "#ffebcd" })
hi(0, "FzfLuaHeaderText", { fg = "#ff4040" })
hi(0, "FzfLuaTabMarker", { bold = true, fg = "#ffebcd" })
hi(0, "FzfLuaTabTitle", { bold = true, fg = "#b0e2ff" })
hi(0, "GitConflictAncestor", { bg = "#68217a", bold = true })
hi(0, "GitConflictAncestorLabel", { bg = "#a634c3" })
hi(0, "GitConflictCurrent", { bg = "#3a4b48", bold = true })
hi(0, "GitConflictCurrentLabel", { bg = "#5c7873" })
hi(0, "GitConflictIncoming", { bg = "#363b2d", bold = true })
hi(0, "GitConflictIncomingLabel", { bg = "#565e48" })
hi(0, "GitSignsAdd", { fg = "#a9b665" })
hi(0, "GitSignsAddPreview", { link = "DiffAdd" })
hi(0, "GitSignsChange", { fg = "#e78a4e" })
hi(0, "GitSignsCurrentLineBlame", { fg = "#404040" })
hi(0, "GitSignsDelete", { fg = "#ea6962" })
hi(0, "GitSignsDeletePreview", { link = "DiffDelete" })
hi(0, "GitSignsStagedAdd", { fg = "#545b32" })
hi(0, "GitSignsStagedAddLn", { bg = "#363b2d" })
hi(0, "GitSignsStagedAddNr", { fg = "#545b32" })
hi(0, "GitSignsStagedChange", { fg = "#734527" })
hi(0, "GitSignsStagedChangeLn", { bg = "#242a2a" })
hi(0, "GitSignsStagedChangeNr", { fg = "#734527" })
hi(0, "GitSignsStagedChangedelete", { fg = "#734527" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#242a2a" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#734527" })
hi(0, "GitSignsStagedDelete", { fg = "#753431" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#753431" })
hi(0, "GitSignsStagedTopdelete", { fg = "#753431" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#753431" })
hi(0, "GlyphPalette1", { fg = "#ea6962" })
hi(0, "GlyphPalette2", { fg = "#89b482" })
hi(0, "GlyphPalette3", { fg = "#d8a657" })
hi(0, "GlyphPalette4", { fg = "#7daea3" })
hi(0, "GlyphPalette6", { fg = "#89b482" })
hi(0, "GlyphPalette7", { fg = "#ebdbb2" })
hi(0, "GlyphPalette9", { fg = "#ea6962" })
hi(0, "HopNextKey", { bg = "#1d2021", bold = true, fg = "#e78a4e", underline = true })
hi(0, "HopNextKey1", { bg = "#1d2021", bold = true, fg = "#7daea3" })
hi(0, "HopNextKey2", { bg = "#1d2021", bold = true, fg = "#89b482", italic = true })
hi(0, "HopUnmatched", { bg = "#1d2021", fg = "#595959" })
hi(0, "IblIndent", { fg = "#292929" })
hi(0, "IblScope", { fg = "#595959" })
hi(0, "Identifier", { fg = "#ea6962" })
hi(0, "Ignore", {})
hi(0, "IlluminatedWordRead", { bg = "#363637" })
hi(0, "IlluminatedWordText", { bg = "#363637" })
hi(0, "IlluminatedWordWrite", { bg = "#363637" })
hi(0, "IncSearch", { bg = "#7ea578", fg = "#191b1c" })
hi(0, "Include", { fg = "#d3869b" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#ea6962" })
hi(0, "Label", { fg = "#e78a4e" })
hi(0, "LineNr", { fg = "#595959" })
hi(0, "LspCodeLens", { fg = "#595959" })
hi(0, "LspDiagnosticsDefaultError", { fg = "#ea6962" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#89b482" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#89b482" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#d8a657" })
hi(0, "LspDiagnosticsError", { fg = "#ea6962" })
hi(0, "LspDiagnosticsHint", { fg = "#89b482" })
hi(0, "LspDiagnosticsInformation", { fg = "#89b482" })
hi(0, "LspDiagnosticsUnderlineError", { sp = "#ea6962", underline = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = "#89b482", underline = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = "#89b482", underline = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = "#d8a657", underline = true })
hi(0, "LspDiagnosticsVirtualTextError", { fg = "#ea6962", italic = true })
hi(0, "LspDiagnosticsVirtualTextHint", { fg = "#89b482", italic = true })
hi(0, "LspDiagnosticsVirtualTextInformation", { fg = "#89b482", italic = true })
hi(0, "LspDiagnosticsVirtualTextWarning", { fg = "#d8a657", italic = true })
hi(0, "LspDiagnosticsWarning", { fg = "#d8a657" })
hi(0, "LspInfoBorder", { link = "FloatBorder" })
hi(0, "LspInlayHint", { bg = "#252626", fg = "#595959" })
hi(0, "LspReferenceRead", { bg = "#404040" })
hi(0, "LspReferenceText", { bg = "#404040" })
hi(0, "LspReferenceWrite", { bg = "#404040" })
hi(0, "LspSignatureActiveParameter", { fg = "#e78a4e" })
hi(0, "Macro", { fg = "#89b482" })
hi(0, "MatchParen", { bg = "#404040", bold = true, fg = "#e78a4e" })
hi(0, "MiniIndentscopeSymbol", { link = "Comment" })
hi(0, "ModeMsg", { bold = true, fg = "#ebdbb2" })
hi(0, "MoreMsg", { fg = "#7daea3" })
hi(0, "MsgSeparator", {})
hi(0, "NeoTreeDimText", { fg = "#928374" })
hi(0, "NeoTreeDirectoryIcon", { fg = "#d5c4a1" })
hi(0, "NeoTreeDirectoryName", { fg = "#d5c4a1" })
hi(0, "NeoTreeExpander", { fg = "#595959" })
hi(0, "NeoTreeFileNameOpened", { fg = "#d3869b" })
hi(0, "NeoTreeFilterTerm", { bold = true, fg = "#a9b665" })
hi(0, "NeoTreeFloatBorder", { link = "TelescopeResultsBorder" })
hi(0, "NeoTreeFloatTitle", { link = "FloatTitle" })
hi(0, "NeoTreeGitAdded", { fg = "#a9b665" })
hi(0, "NeoTreeGitConflict", { fg = "#ea6962" })
hi(0, "NeoTreeGitDeleted", { fg = "#ea6962" })
hi(0, "NeoTreeGitIgnored", { fg = "#595959" })
hi(0, "NeoTreeGitModified", { fg = "#e78a4e" })
hi(0, "NeoTreeGitStaged", { fg = "#a9b665" })
hi(0, "NeoTreeGitUnstaged", { fg = "#ea6962" })
hi(0, "NeoTreeGitUntracked", { fg = "#a9b665" })
hi(0, "NeoTreeIndent", { fg = "#404040" })
hi(0, "NeoTreeIndentMarker", { fg = "#595959" })
hi(0, "NeoTreeModified", { fg = "#e78a4e" })
hi(0, "NeoTreeNormal", { bg = "#191b1c", fg = "#ebdbb2" })
hi(0, "NeoTreeNormalNC", { bg = "#191b1c", fg = "#ebdbb2" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#d5c4a1" })
hi(0, "NeoTreeStatusLineNC", { bg = "#191b1c", fg = "#191b1c" })
hi(0, "NeoTreeSymbolicLinkTarget", { fg = "#d3869b" })
hi(0, "NeoTreeTabActive", { bg = "#191b1c", bold = true, fg = "#ebdbb2" })
hi(0, "NeoTreeTabInactive", { bg = "#141617", fg = "#4d4d4d" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#191b1c", fg = "#191b1c" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#141617", fg = "#141617" })
hi(0, "NeoTreeTitleBar", { bg = "#7daea3", fg = "#191b1c" })
hi(0, "NeoTreeVertSplit", { bg = "#1d2021", fg = "#1d2021" })
hi(0, "NeoTreeWinSeparator", { bg = "#1d2021", fg = "#1d2021" })
hi(0, "NeogitBranch", { bold = true, fg = "#e78a4e" })
hi(0, "NeogitChangeAdded", { bold = true, fg = "#a9b665" })
hi(0, "NeogitChangeBothModified", { bold = true, fg = "#d8a657" })
hi(0, "NeogitChangeCopied", { bold = true, fg = "#d3869b" })
hi(0, "NeogitChangeDeleted", { bold = true, fg = "#ea6962" })
hi(0, "NeogitChangeModified", { bold = true, fg = "#7daea3" })
hi(0, "NeogitChangeNewFile", { bold = true, fg = "#a9b665" })
hi(0, "NeogitChangeRenamed", { bold = true, fg = "#d3869b" })
hi(0, "NeogitChangeUpdated", { bold = true, fg = "#e78a4e" })
hi(0, "NeogitCommitViewHeader", { bg = "#3a4b48", fg = "#93b7a6" })
hi(0, "NeogitDiffAdd", { bg = "#2a2e27", fg = "#8d9857" })
hi(0, "NeogitDiffAddHighlight", { bg = "#4d5438", fg = "#b3bc71" })
hi(0, "NeogitDiffContext", { bg = "#1d2021" })
hi(0, "NeogitDiffContextHighlight", { bg = "#292929" })
hi(0, "NeogitDiffDelete", { bg = "#302727", fg = "#c15a55" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#643937", fg = "#ea7a6e" })
hi(0, "NeogitDiffHeader", { bg = "#1d2021", bold = true, fg = "#7daea3" })
hi(0, "NeogitDiffHeaderHighlight", { bg = "#1d2021", bold = true, fg = "#e78a4e" })
hi(0, "NeogitFilePath", { fg = "#7daea3", italic = true })
hi(0, "NeogitGraphBlue", { fg = "#7daea3" })
hi(0, "NeogitGraphBoldBlue", { bold = true, fg = "#7daea3" })
hi(0, "NeogitGraphBoldCyan", { bold = true, fg = "#7daea3" })
hi(0, "NeogitGraphBoldGray", { bold = true, fg = "#d5c4a1" })
hi(0, "NeogitGraphBoldGreen", { bold = true, fg = "#a9b665" })
hi(0, "NeogitGraphBoldPurple", { bold = true, fg = "#7daea3" })
hi(0, "NeogitGraphBoldRed", { bold = true, fg = "#ea6962" })
hi(0, "NeogitGraphBoldWhite", { bold = true })
hi(0, "NeogitGraphBoldYellow", { bold = true, fg = "#d8a657" })
hi(0, "NeogitGraphCyan", { fg = "#7daea3" })
hi(0, "NeogitGraphGray", { fg = "#d5c4a1" })
hi(0, "NeogitGraphGreen", { fg = "#a9b665" })
hi(0, "NeogitGraphOrange", { fg = "#e78a4e" })
hi(0, "NeogitGraphPurple", { fg = "#7daea3" })
hi(0, "NeogitGraphRed", { fg = "#ea6962" })
hi(0, "NeogitGraphWhite", { fg = "#1d2021" })
hi(0, "NeogitGraphYellow", { fg = "#d8a657" })
hi(0, "NeogitHunkHeader", { bg = "#262d2d", fg = "#4d6762" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#323f3d", fg = "#7daea3" })
hi(0, "NeogitNotificationError", { fg = "#ea6962" })
hi(0, "NeogitNotificationInfo", { fg = "#7daea3" })
hi(0, "NeogitNotificationWarning", { fg = "#d8a657" })
hi(0, "NeogitObjectId", { link = "Comment" })
hi(0, "NeogitPopupActionKey", { fg = "#7daea3" })
hi(0, "NeogitPopupBold", { bold = true })
hi(0, "NeogitPopupConfigKey", { fg = "#7daea3" })
hi(0, "NeogitPopupOptionKey", { fg = "#7daea3" })
hi(0, "NeogitPopupSwitchKey", { fg = "#7daea3" })
hi(0, "NeogitRebaseDone", { link = "Comment" })
hi(0, "NeogitRebasing", { bold = true, fg = "#d3869b" })
hi(0, "NeogitRecentcommits", { bold = true, fg = "#d3869b" })
hi(0, "NeogitRemote", { bold = true, fg = "#a9b665" })
hi(0, "NeogitSectionHeader", { bold = true, fg = "#d3869b" })
hi(0, "NeogitStagedchanges", { bold = true, fg = "#d3869b" })
hi(0, "NeogitStash", { link = "Comment" })
hi(0, "NeogitStashes", { bold = true, fg = "#d3869b" })
hi(0, "NeogitTagDistance", { fg = "#7daea3" })
hi(0, "NeogitTagName", { fg = "#d8a657" })
hi(0, "NeogitUnmergedInto", { link = "Function" })
hi(0, "NeogitUnmergedchanges", { bold = true, fg = "#d3869b" })
hi(0, "NeogitUnpulledFrom", { link = "Function" })
hi(0, "NeogitUnpulledchanges", { bold = true, fg = "#d3869b" })
hi(0, "NeogitUnpushedTo", { bold = true, fg = "#7daea3" })
hi(0, "NeogitUnstagedchanges", { bold = true, fg = "#d3869b" })
hi(0, "NeogitUntrackedfiles", { bold = true, fg = "#d3869b" })
hi(0, "NoiceFormatProgressDone", { bg = "#3d4c3e", fg = "#ebdbb2" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = "#595959" })
hi(0, "Normal", { bg = "#1d2021", fg = "#ebdbb2" })
hi(0, "NormalFloat", { bg = "#1d2021", fg = "#ebdbb2" })
hi(0, "NormalNC", { bg = "#1d2021", fg = "#ebdbb2" })
hi(0, "NormalSB", { bg = "#141617", fg = "#ebdbb2" })
hi(0, "NotifyDEBUGBorder", { fg = "#8b8b8b" })
hi(0, "NotifyDEBUGIcon", { fg = "#8b8b8b" })
hi(0, "NotifyDEBUGTitle", { fg = "#8b8b8b" })
hi(0, "NotifyERRORBorder", { fg = "#8a1f1f" })
hi(0, "NotifyERRORIcon", { fg = "#f70067" })
hi(0, "NotifyERRORTitle", { fg = "#f70067" })
hi(0, "NotifyINFOBorder", { fg = "#4f6752" })
hi(0, "NotifyINFOIcon", { fg = "#a9ff68" })
hi(0, "NotifyINFOTitle", { fg = "#a9ff68" })
hi(0, "NotifyTRACEBorder", { fg = "#4f3552" })
hi(0, "NotifyTRACEIcon", { fg = "#d484ff" })
hi(0, "NotifyTRACETitle", { fg = "#d484ff" })
hi(0, "NotifyWARNBorder", { fg = "#79491d" })
hi(0, "NotifyWARNIcon", { fg = "#f79000" })
hi(0, "NotifyWARNTitle", { fg = "#f79000" })
hi(0, "Number", { fg = "#d3869b" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#7daea3" })
hi(0, "NvimTreeFolderIcon", { fg = "#7daea3" })
hi(0, "NvimTreeFolderName", { fg = "#7daea3" })
hi(0, "NvimTreeGitDeleted", { fg = "#ea6962" })
hi(0, "NvimTreeGitDirty", { fg = "#d8a657" })
hi(0, "NvimTreeGitNew", { fg = "#7daea3" })
hi(0, "NvimTreeImageFile", { fg = "#ebdbb2" })
hi(0, "NvimTreeIndentMarker", { fg = "#595959" })
hi(0, "NvimTreeNormal", { bg = "#191b1c", fg = "#ebdbb2" })
hi(0, "NvimTreeOpenedFile", { fg = "#d3869b" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#7daea3" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#7daea3" })
hi(0, "NvimTreeSpecialFile", { fg = "#ea6962" })
hi(0, "NvimTreeStatuslineNc", { bg = "#191b1c", fg = "#191b1c" })
hi(0, "NvimTreeSymlink", { fg = "#d3869b" })
hi(0, "NvimTreeWinSeparator", { bg = "#1d2021", fg = "#1d2021" })
hi(0, "Operator", { fg = "#e78a4e" })
hi(0, "Pmenu", { bg = "#191b1c" })
hi(0, "PmenuSbar", { bg = "#404040" })
hi(0, "PmenuSel", { bg = "#292929", bold = true })
hi(0, "PmenuThumb", { bg = "#595959" })
hi(0, "PreCondit", { fg = "#d3869b" })
hi(0, "PreProc", { fg = "#d3869b" })
hi(0, "Question", { fg = "#7daea3" })
hi(0, "QuickFixLine", { bg = "#404040", bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#7daea3" })
hi(0, "RainbowDelimiterCyan", { fg = "#89b482" })
hi(0, "RainbowDelimiterGreen", { fg = "#a9b665" })
hi(0, "RainbowDelimiterOrange", { fg = "#e78a4e" })
hi(0, "RainbowDelimiterRed", { fg = "#ea6962" })
hi(0, "RainbowDelimiterViolet", { fg = "#d3869b" })
hi(0, "RainbowDelimiterYellow", { fg = "#d8a657" })
hi(0, "Repeat", { fg = "#ea6962" })
hi(0, "Search", { bg = "#3d4c3e", fg = "#ebdbb2" })
hi(0, "SignColumn", { fg = "#404040" })
hi(0, "SignColumnSB", { bg = "#141617", fg = "#404040" })
hi(0, "Special", { fg = "#d8a657" })
hi(0, "SpecialChar", { fg = "#d8a657" })
hi(0, "SpecialKey", { link = "NonText" })
hi(0, "SpellBad", { sp = "#ea6962", undercurl = true })
hi(0, "SpellCap", { sp = "#d8a657", undercurl = true })
hi(0, "SpellLocal", { sp = "#7daea3", undercurl = true })
hi(0, "SpellRare", { sp = "#a9b665", undercurl = true })
hi(0, "Statement", { fg = "#ea6962" })
hi(0, "StorageClass", { fg = "#e78a4e" })
hi(0, "String", { fg = "#a9b665" })
hi(0, "Structure", { fg = "#e78a4e" })
hi(0, "Substitute", { bg = "#404040", fg = "#d3869b" })
hi(0, "TSAnnotation", { fg = "#d3869b" })
hi(0, "TSAttribute", { fg = "#d3869b" })
hi(0, "TSBoolean", { fg = "#d3869b" })
hi(0, "TSCharacter", { fg = "#89b482" })
hi(0, "TSCharacterSpecial", { link = "SpecialChar" })
hi(0, "TSComment", { link = "Comment" })
hi(0, "TSConditional", { fg = "#ea6962" })
hi(0, "TSConstBuiltin", { fg = "#d3869b" })
hi(0, "TSConstMacro", { fg = "#d3869b" })
hi(0, "TSConstant", { fg = "#ebdbb2" })
hi(0, "TSConstructor", { fg = "#a9b665" })
hi(0, "TSDebug", { link = "Debug" })
hi(0, "TSDefine", { link = "Define" })
hi(0, "TSEnvironment", { link = "Macro" })
hi(0, "TSEnvironmentName", { link = "Type" })
hi(0, "TSError", { link = "Error" })
hi(0, "TSException", { fg = "#ea6962" })
hi(0, "TSField", { fg = "#7daea3" })
hi(0, "TSFloat", { fg = "#d3869b" })
hi(0, "TSFuncBuiltin", { fg = "#a9b665" })
hi(0, "TSFuncMacro", { fg = "#a9b665" })
hi(0, "TSFunction", { fg = "#a9b665" })
hi(0, "TSFunctionCall", { fg = "#a9b665" })
hi(0, "TSInclude", { fg = "#ea6962" })
hi(0, "TSKeyword", { fg = "#ea6962" })
hi(0, "TSKeywordFunction", { fg = "#ea6962" })
hi(0, "TSKeywordOperator", { fg = "#e78a4e" })
hi(0, "TSKeywordReturn", { fg = "#ea6962" })
hi(0, "TSLabel", { fg = "#e78a4e" })
hi(0, "TSLiteral", { link = "String" })
hi(0, "TSMath", { fg = "#7daea3" })
hi(0, "TSMethod", { fg = "#a9b665" })
hi(0, "TSMethodCall", { fg = "#a9b665" })
hi(0, "TSNamespace", { fg = "#d8a657" })
hi(0, "TSNone", { fg = "#ebdbb2" })
hi(0, "TSNumber", { fg = "#d3869b" })
hi(0, "TSOperator", { fg = "#e78a4e" })
hi(0, "TSParameter", { fg = "#ebdbb2" })
hi(0, "TSParameterReference", { fg = "#ebdbb2" })
hi(0, "TSPreProc", { link = "PreProc" })
hi(0, "TSProperty", { fg = "#7daea3" })
hi(0, "TSPunctBracket", { fg = "#ebdbb2" })
hi(0, "TSPunctDelimiter", { link = "Delimiter" })
hi(0, "TSPunctSpecial", { fg = "#7daea3" })
hi(0, "TSRepeat", { fg = "#ea6962" })
hi(0, "TSStorageClass", { fg = "#e78a4e" })
hi(0, "TSStorageClassLifetime", { fg = "#e78a4e" })
hi(0, "TSString", { fg = "#89b482" })
hi(0, "TSStringEscape", { fg = "#a9b665" })
hi(0, "TSStringRegex", { fg = "#a9b665" })
hi(0, "TSStringSpecial", { link = "SpecialChar" })
hi(0, "TSSymbol", { fg = "#ebdbb2" })
hi(0, "TSTag", { fg = "#e78a4e" })
hi(0, "TSTagAttribute", { fg = "#a9b665" })
hi(0, "TSTagDelimiter", { fg = "#a9b665" })
hi(0, "TSText", { fg = "#a9b665" })
hi(0, "TSTextReference", { link = "Constant" })
hi(0, "TSTitle", { link = "Title" })
hi(0, "TSTodo", { link = "Todo" })
hi(0, "TSType", { bold = true, fg = "#d8a657" })
hi(0, "TSTypeBuiltin", { bold = true, fg = "#d8a657" })
hi(0, "TSTypeDefinition", { bold = true, fg = "#d8a657" })
hi(0, "TSTypeQualifier", { bold = true, fg = "#e78a4e" })
hi(0, "TSURI", { fg = "#7daea3" })
hi(0, "TSVariable", { fg = "#ebdbb2" })
hi(0, "TSVariableBuiltin", { fg = "#d3869b" })
hi(0, "TabLine", { bg = "#191b1c", fg = "#404040" })
hi(0, "TabLineFill", {})
hi(0, "TabLineSel", { bg = "#404040", fg = "#a9b665" })
hi(0, "Tag", { bold = true, fg = "#e78a4e" })
hi(0, "TelescopeBorder", { link = "FloatBorder" })
hi(0, "TelescopeMatching", { fg = "#7daea3" })
hi(0, "TelescopePreviewBorder", { bg = "#141617", fg = "#141617" })
hi(0, "TelescopePreviewNormal", { bg = "#141617" })
hi(0, "TelescopePreviewTitle", { bg = "#141617", fg = "#141617" })
hi(0, "TelescopePromptBorder", { bg = "#292929", fg = "#292929" })
hi(0, "TelescopePromptCounter", { bold = true, fg = "#d3869b" })
hi(0, "TelescopePromptNormal", { bg = "#292929" })
hi(0, "TelescopePromptPrefix", { bg = "#292929" })
hi(0, "TelescopePromptTitle", { bg = "#292929", fg = "#292929" })
hi(0, "TelescopeResultsBorder", { bg = "#191b1c", fg = "#191b1c" })
hi(0, "TelescopeResultsNormal", { bg = "#191b1c" })
hi(0, "TelescopeResultsTitle", { bg = "#191b1c", fg = "#191b1c" })
hi(0, "TelescopeSelection", { bg = "#292929", bold = true, fg = "#ebdbb2" })
hi(0, "TelescopeSelectionCaret", { fg = "#ea6962" })
hi(0, "Title", { bold = true, fg = "#e78a4e" })
hi(0, "Todo", { bg = "#ea6962", bold = true, fg = "#1d2021" })
hi(0, "TreesitterContextBottom", { sp = "#292929", underline = true })
hi(0, "TreesitterContextLineNumber", { bg = "#191b1c", fg = "#404040" })
hi(0, "Type", { bold = true, fg = "#d8a657" })
hi(0, "Typedef", { fg = "#ea6962" })
hi(0, "UfoFoldedEllipsis", { bg = "#7daea3", fg = "#141617" })
hi(0, "UfoFoldedFg", { fg = "#7daea3" })
hi(0, "VertSplit", { bg = "#1d2021", fg = "#292929" })
hi(0, "VimwikiHR", { fg = "#d8a657" })
hi(0, "VimwikiHeader1", { bold = true, fg = "#e78a4e" })
hi(0, "VimwikiHeader2", { bold = true, fg = "#a9b665" })
hi(0, "VimwikiHeader3", { bold = true, fg = "#7daea3" })
hi(0, "VimwikiHeader4", { bold = true, fg = "#89b482" })
hi(0, "VimwikiHeader5", { bold = true, fg = "#d8a657" })
hi(0, "VimwikiHeader6", { bold = true, fg = "#d3869b" })
hi(0, "VimwikiLink", { fg = "#89b482" })
hi(0, "VimwikiList", { fg = "#e78a4e" })
hi(0, "VimwikiMarkers", { fg = "#bdae93" })
hi(0, "VimwikiTag", { fg = "#e78a4e" })
hi(0, "Visual", { bg = "#404040", bold = true })
hi(0, "VisualNOS", { bg = "#404040", bold = true })
hi(0, "WarningMsg", { fg = "#d8a657" })
hi(0, "WhichKey", { link = "NormalFloat" })
hi(0, "WhichKeyBorder", { link = "FloatBorder" })
hi(0, "WhichKeyDesc", { fg = "#d3869b" })
hi(0, "WhichKeyFloat", { bg = "#191b1c" })
hi(0, "WhichKeyGroup", { fg = "#7daea3" })
hi(0, "WhichKeySeparator", { fg = "#595959" })
hi(0, "WhichKeyValue", { fg = "#595959" })
hi(0, "Whitespace", { fg = "#404040" })
hi(0, "WildMenu", { bg = "#595959" })
hi(0, "WinBar", { fg = "#ea6962" })
hi(0, "WinBarNC", { link = "WinBar" })
hi(0, "WinSeparator", { fg = "#141617" })
hi(0, "YankHighlight", { bg = "#4d4d4d" })
hi(0, "debugBreakpoint", { bg = "#1d2021", fg = "#595959" })
hi(0, "debugPC", { bg = "#141617" })
hi(0, "diffAdded", { fg = "#a9b665" })
hi(0, "diffChanged", { fg = "#7daea3" })
hi(0, "diffFile", { fg = "#7daea3" })
hi(0, "diffIndexLine", { fg = "#89b482" })
hi(0, "diffLine", { fg = "#595959" })
hi(0, "diffNewFile", { fg = "#e78a4e" })
hi(0, "diffOldFile", { fg = "#d8a657" })
hi(0, "diffRemoved", { fg = "#ea6962" })
hi(0, "gitCommitSummary", { fg = "#ea6962", italic = true })
hi(0, "healthError", { fg = "#ea6962" })
hi(0, "healthSuccess", { fg = "#89b482" })
hi(0, "healthWarning", { fg = "#d8a657" })
hi(0, "htmlH1", { bold = true, fg = "#d3869b" })
hi(0, "htmlH2", { bold = true, fg = "#7daea3" })
hi(0, "illuminatedCurWord", { bg = "#404040" })
hi(0, "illuminatedWord", { bg = "#404040" })
hi(0, "lCursor", { bg = "#ebdbb2", fg = "#1d2021" })
hi(0, "markdownCode", { fg = "#ea6962" })
hi(0, "markdownCodeBlock", { fg = "#ea6962" })
hi(0, "markdownH1", { link = "rainbow1" })
hi(0, "markdownH2", { link = "rainbow2" })
hi(0, "markdownH3", { link = "rainbow3" })
hi(0, "markdownH4", { link = "rainbow4" })
hi(0, "markdownH5", { link = "rainbow5" })
hi(0, "markdownH6", { link = "rainbow6" })
hi(0, "markdownHeadingDelimiter", { bold = true, fg = "#e78a4e" })
hi(0, "markdownLinkText", { fg = "#7daea3", underline = true })
hi(0, "mkdCodeDelimiter", { bg = "#1d2021", fg = "#ebdbb2" })
hi(0, "mkdCodeEnd", { bold = true, fg = "#ea6962" })
hi(0, "mkdCodeStart", { bold = true, fg = "#ea6962" })
hi(0, "qfFileName", { fg = "#7daea3" })
hi(0, "qfLineNr", { fg = "#d8a657" })
hi(0, "rainbow1", { fg = "#ea6962" })
hi(0, "rainbow2", { fg = "#e78a4e" })
hi(0, "rainbow3", { fg = "#d8a657" })
hi(0, "rainbow4", { fg = "#a9b665" })
hi(0, "rainbow5", { fg = "#89b482" })
hi(0, "rainbow6", { fg = "#7daea3" })
hi(0, "zshKSHFunction", { link = "Function" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#1c1c1c"
g.terminal_color_1 = "#d75f5f"
g.terminal_color_2 = "#87af87"
g.terminal_color_3 = "#afaf87"
g.terminal_color_4 = "#5f87af"
g.terminal_color_5 = "#af87af"
g.terminal_color_6 = "#5f8787"
g.terminal_color_7 = "#9e9e9e"
g.terminal_color_8 = "#767676"
g.terminal_color_9 = "#d7875f"
g.terminal_color_10 = "#afd7af"
g.terminal_color_11 = "#d7d787"
g.terminal_color_12 = "#87afd7"
g.terminal_color_13 = "#d7afd7"
g.terminal_color_14 = "#87afaf"
g.terminal_color_15 = "#bcbcbc"
