-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
	vim.cmd("highlight clear")
end
vim.g.colors_name = "gruvbox"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "PreProc" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.error", { link = "ErrorMsg" })
hi(0, "@comment.note", { link = "SpecialComment" })
hi(0, "@comment.todo", { link = "Todo" })
hi(0, "@comment.warning", { link = "WarningMsg" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constant.macro", { link = "Define" })
hi(0, "@diff.delta", { link = "diffChanged" })
hi(0, "@diff.minus", { link = "diffRemoved" })
hi(0, "@diff.plus", { link = "diffAdded" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@function.method", { link = "Function" })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.debug", { link = "Debug" })
hi(0, "@keyword.directive", { link = "PreProc" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.function", { link = "Keyword" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.operator", { link = "GruvboxRed" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.return", { link = "Keyword" })
hi(0, "@keyword.storage", { link = "StorageClass" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@macro" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@constructor" })
hi(0, "@lsp.type.macro", { link = "@macro" })
hi(0, "@lsp.type.method", { link = "@method" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@markup", { link = "GruvboxFg1" })
hi(0, "@markup.emphasis", { italic = true })
hi(0, "@markup.environment", { link = "Macro" })
hi(0, "@markup.environment.name", { link = "Type" })
hi(0, "@markup.heading", { link = "Title" })
hi(0, "@markup.link", { link = "Underlined" })
hi(0, "@markup.link.label", { link = "SpecialChar" })
hi(0, "@markup.list", { link = "Delimiter" })
hi(0, "@markup.list.checked", { link = "GruvboxGreen" })
hi(0, "@markup.list.unchecked", { link = "GruvboxGray" })
hi(0, "@markup.math", { link = "Special" })
hi(0, "@markup.raw", { link = "String" })
hi(0, "@markup.strike", { strikethrough = true })
hi(0, "@markup.strong", {})
hi(0, "@markup.underline", {})
hi(0, "@method.call", { link = "Function" })
hi(0, "@module", { link = "GruvboxFg1" })
hi(0, "@namespace", { link = "GruvboxFg1" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@punctuation.bracket", { link = "Delimiter" })
hi(0, "@punctuation.delimiter", { link = "Delimiter" })
hi(0, "@punctuation.special", { link = "Delimiter" })
hi(0, "@string.escape", { link = "SpecialChar" })
hi(0, "@string.regex", { link = "String" })
hi(0, "@string.regexp", { link = "String" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.path", { link = "Underlined" })
hi(0, "@string.special.symbol", { link = "Identifier" })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@structure", { link = "Structure" })
hi(0, "@symbol", { link = "Identifier" })
hi(0, "@tag.attribute", { link = "Identifier" })
hi(0, "@tag.delimiter", { link = "Delimiter" })
hi(0, "@text", { link = "GruvboxFg1" })
hi(0, "@text.danger", { link = "ErrorMsg" })
hi(0, "@text.danger.comment", { bg = "#fb4934", fg = "#fbf1c7" })
hi(0, "@text.diff.add", { link = "diffAdded" })
hi(0, "@text.diff.delete", { link = "diffRemoved" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.environment", { link = "Macro" })
hi(0, "@text.environment.name", { link = "Type" })
hi(0, "@text.literal", { link = "String" })
hi(0, "@text.math", { link = "Special" })
hi(0, "@text.note", { link = "SpecialComment" })
hi(0, "@text.note.comment", { fg = "#d3869b" })
hi(0, "@text.reference", { link = "Constant" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", {})
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.todo.checked", { link = "GruvboxGreen" })
hi(0, "@text.todo.unchecked", { link = "GruvboxGray" })
hi(0, "@text.underline", {})
hi(0, "@text.uri", { link = "Underlined" })
hi(0, "@text.warning", { link = "WarningMsg" })
hi(0, "@type.builtin", { link = "Type" })
hi(0, "@type.definition", { link = "Typedef" })
hi(0, "@type.qualifier", { link = "Type" })
hi(0, "@variable", { link = "GruvboxFg1" })
hi(0, "@variable.builtin", { link = "Special" })
hi(0, "@variable.member", { link = "Identifier" })
hi(0, "@variable.parameter", { link = "Identifier" })
hi(0, "Boolean", { link = "GruvboxPurple" })
hi(0, "CarbonBrokenSymlink", { link = "GruvboxRed" })
hi(0, "CarbonDanger", { link = "GruvboxRed" })
hi(0, "CarbonExe", { link = "GruvboxYellow" })
hi(0, "CarbonFile", { link = "GruvboxFg1" })
hi(0, "CarbonIndicator", { link = "GruvboxGray" })
hi(0, "CarbonPending", { link = "GruvboxYellow" })
hi(0, "CarbonSymlink", { link = "GruvboxAqua" })
hi(0, "Character", { link = "GruvboxPurple" })
hi(0, "CmpItemAbbr", { link = "GruvboxFg0" })
hi(0, "CmpItemAbbrDefault", { fg = "#ebdbb2" })
hi(0, "CmpItemAbbrDeprecated", { link = "GruvboxFg1" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#928374" })
hi(0, "CmpItemAbbrMatch", { link = "GruvboxBlueBold" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#ebdbb2" })
hi(0, "CmpItemAbbrMatchFuzzy", { link = "GruvboxBlueUnderline" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#ebdbb2" })
hi(0, "CmpItemKindClass", { link = "GruvboxYellow" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { link = "GruvboxPurple" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { link = "GruvboxOrange" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { link = "GruvboxYellow" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnum", { link = "GruvboxYellow" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { link = "GruvboxAqua" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { link = "GruvboxPurple" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { link = "GruvboxBlue" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { link = "GruvboxBlue" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { link = "GruvboxBlue" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "GruvboxBlue" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "GruvboxYellow" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { link = "GruvboxPurple" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "GruvboxBlue" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "GruvboxBlue" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { link = "GruvboxYellow" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { link = "GruvboxBlue" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { link = "GruvboxPurple" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { link = "GruvboxGreen" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { link = "GruvboxYellow" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { link = "GruvboxOrange" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { link = "GruvboxYellow" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { link = "GruvboxBlue" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { link = "GruvboxOrange" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { link = "GruvboxOrange" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { link = "GruvboxGray" })
hi(0, "CmpItemMenuDefault", { fg = "#ebdbb2" })
hi(0, "CocCodeLens", { link = "GruvboxGray" })
hi(0, "CocDiagnosticsError", { link = "GruvboxRed" })
hi(0, "CocDiagnosticsHint", { link = "GruvboxAqua" })
hi(0, "CocDiagnosticsInfo", { link = "GruvboxBlue" })
hi(0, "CocDiagnosticsWarning", { link = "GruvboxOrange" })
hi(0, "CocErrorFloat", { link = "GruvboxRed" })
hi(0, "CocErrorHighlight", { link = "GruvboxRedUnderline" })
hi(0, "CocErrorSign", { link = "GruvboxRedSign" })
hi(0, "CocHintFloat", { link = "GruvboxAqua" })
hi(0, "CocHintHighlight", { link = "GruvboxAquaUnderline" })
hi(0, "CocHintSign", { link = "GruvboxAquaSign" })
hi(0, "CocInfoFloat", { link = "GruvboxBlue" })
hi(0, "CocInfoHighlight", { link = "GruvboxBlueUnderline" })
hi(0, "CocInfoSign", { link = "GruvboxBlueSign" })
hi(0, "CocMenuSel", { link = "PmenuSel" })
hi(0, "CocSelectedText", { link = "GruvboxRed" })
hi(0, "CocWarningFloat", { link = "GruvboxOrange" })
hi(0, "CocWarningHighlight", { link = "GruvboxOrangeUnderline" })
hi(0, "CocWarningSign", { link = "GruvboxOrangeSign" })
hi(0, "ColorColumn", { bg = "#3c3836" })
hi(0, "Comment", { fg = "#928374", italic = true })
hi(0, "Conceal", { fg = "#83a598" })
hi(0, "Conditional", { link = "GruvboxRed" })
hi(0, "Constant", { link = "GruvboxPurple" })
hi(0, "CurSearch", { link = "IncSearch" })
hi(0, "Cursor", { reverse = true })
hi(0, "CursorColumn", { link = "CursorLine" })
hi(0, "CursorLine", { bg = "#3c3836" })
hi(0, "CursorLineNr", { bg = "#3c3836", fg = "#fabd2f" })
hi(0, "DapBreakpointSymbol", { bg = "#3c3836", fg = "#fb4934" })
hi(0, "DapStoppedSymbol", { bg = "#3c3836", fg = "#b8bb26" })
hi(0, "DapUIBreakpointsCurrentLine", { link = "GruvboxYellow" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "GruvboxGray" })
hi(0, "DapUIBreakpointsInfo", { link = "GruvboxAqua" })
hi(0, "DapUIBreakpointsLine", { link = "GruvboxYellow" })
hi(0, "DapUIBreakpointsPath", { link = "GruvboxBlue" })
hi(0, "DapUICurrentFrameName", { link = "GruvboxPurple" })
hi(0, "DapUIDecoration", { link = "GruvboxPurple" })
hi(0, "DapUIEndofBuffer", { link = "GruvboxBg2" })
hi(0, "DapUIFloatBorder", { link = "GruvboxAqua" })
hi(0, "DapUILineNumber", { link = "GruvboxYellow" })
hi(0, "DapUIModifiedValue", { link = "GruvboxRed" })
hi(0, "DapUINormalNC", { bg = "#282828", fg = "#ebdbb2" })
hi(0, "DapUIPlayPause", { bg = "#3c3836", fg = "#b8bb26" })
hi(0, "DapUIPlayPauseNC", { bg = "#3c3836", fg = "#b8bb26" })
hi(0, "DapUIRestart", { bg = "#3c3836", fg = "#b8bb26" })
hi(0, "DapUIRestartNC", { bg = "#3c3836", fg = "#b8bb26" })
hi(0, "DapUIScope", { link = "GruvboxBlue" })
hi(0, "DapUISource", { link = "GruvboxFg1" })
hi(0, "DapUIStepBack", { bg = "#3c3836", fg = "#83a598" })
hi(0, "DapUIStepBackNC", { bg = "#3c3836", fg = "#83a598" })
hi(0, "DapUIStepInto", { bg = "#3c3836", fg = "#83a598" })
hi(0, "DapUIStepIntoNC", { bg = "#3c3836", fg = "#83a598" })
hi(0, "DapUIStepOut", { bg = "#3c3836", fg = "#83a598" })
hi(0, "DapUIStepOutNC", { bg = "#3c3836", fg = "#83a598" })
hi(0, "DapUIStepOver", { bg = "#3c3836", fg = "#83a598" })
hi(0, "DapUIStepOverNC", { bg = "#3c3836", fg = "#83a598" })
hi(0, "DapUIStop", { bg = "#3c3836", fg = "#fb4934" })
hi(0, "DapUIStopNC", { bg = "#3c3836", fg = "#fb4934" })
hi(0, "DapUIStoppedThread", { link = "GruvboxBlue" })
hi(0, "DapUIThread", { link = "GruvboxBlue" })
hi(0, "DapUIType", { link = "GruvboxOrange" })
hi(0, "DapUIUnavailable", { link = "GruvboxGray" })
hi(0, "DapUIUnavailableNC", { fg = "#928374" })
hi(0, "DapUIWatchesEmpty", { link = "GruvboxGray" })
hi(0, "DapUIWatchesError", { link = "GruvboxRed" })
hi(0, "DapUIWatchesValue", { link = "GruvboxYellow" })
hi(0, "DapUIWinSelect", { link = "GruvboxYellow" })
hi(0, "DashboardCenter", { link = "GruvboxYellow" })
hi(0, "DashboardFooter", { fg = "#d3869b", italic = true })
hi(0, "DashboardHeader", { link = "GruvboxAqua" })
hi(0, "DashboardShortCut", { link = "GruvboxOrange" })
hi(0, "Define", { link = "GruvboxAqua" })
hi(0, "DiagnosticError", { link = "GruvboxRed" })
hi(0, "DiagnosticFloatingError", { link = "GruvboxRed" })
hi(0, "DiagnosticFloatingHint", { link = "GruvboxAqua" })
hi(0, "DiagnosticFloatingInfo", { link = "GruvboxBlue" })
hi(0, "DiagnosticFloatingWarn", { link = "GruvboxOrange" })
hi(0, "DiagnosticHint", { link = "GruvboxAqua" })
hi(0, "DiagnosticInfo", { link = "GruvboxBlue" })
hi(0, "DiagnosticOk", { link = "GruvboxGreenSign" })
hi(0, "DiagnosticSignError", { link = "GruvboxRedSign" })
hi(0, "DiagnosticSignHint", { link = "GruvboxAquaSign" })
hi(0, "DiagnosticSignInfo", { link = "GruvboxBlueSign" })
hi(0, "DiagnosticSignWarn", { link = "GruvboxYellowSign" })
hi(0, "DiagnosticUnderlineError", { link = "GruvboxRedUnderline" })
hi(0, "DiagnosticUnderlineHint", { link = "GruvboxAquaUnderline" })
hi(0, "DiagnosticUnderlineInfo", { link = "GruvboxBlueUnderline" })
hi(0, "DiagnosticUnderlineWarn", { link = "GruvboxYellowUnderline" })
hi(0, "DiagnosticVirtualTextError", { link = "GruvboxRed" })
hi(0, "DiagnosticVirtualTextHint", { link = "GruvboxAqua" })
hi(0, "DiagnosticVirtualTextInfo", { link = "GruvboxBlue" })
hi(0, "DiagnosticVirtualTextWarn", { link = "GruvboxYellow" })
hi(0, "DiagnosticWarn", { link = "GruvboxYellow" })
hi(0, "DiffAdd", { bg = "#62693e" })
hi(0, "DiffChange", { bg = "#49503b" })
hi(0, "DiffDelete", { bg = "#722529" })
hi(0, "DiffText", { bg = "#fabd2f", fg = "#282828" })
hi(0, "DiffviewFilePanelDeletions", { link = "GruvboxRedBold" })
hi(0, "DiffviewFilePanelInsertions", { link = "GruvboxGreenBold" })
hi(0, "DiffviewStatusModified", { link = "GruvboxGreenBold" })
hi(0, "Directory", { link = "GruvboxBlueBold" })
hi(0, "DirvishArg", { link = "GruvboxYellow" })
hi(0, "DirvishPathTail", { link = "GruvboxAqua" })
hi(0, "Done", { fg = "#fe8019", italic = true })
hi(0, "Error", { fg = "#fb4934", reverse = true })
hi(0, "ErrorMsg", { bg = "#fb4934", fg = "#282828" })
hi(0, "Exception", { link = "GruvboxRed" })
hi(0, "FinderSeparator", { link = "GruvboxAqua" })
hi(0, "Float", { link = "GruvboxPurple" })
hi(0, "FoldColumn", { bg = "#3c3836", fg = "#928374" })
hi(0, "Folded", { bg = "#3c3836", fg = "#928374", italic = true })
hi(0, "Function", { link = "GruvboxGreenBold" })
hi(0, "GitConflictAncestor", { bg = "#68217a", bold = true })
hi(0, "GitConflictAncestorLabel", { bg = "#a634c3" })
hi(0, "GitConflictCurrent", { bg = "#fabd2f", bold = true })
hi(0, "GitConflictCurrentLabel", { bg = "#ffff4b" })
hi(0, "GitConflictIncoming", { bg = "#62693e", bold = true })
hi(0, "GitConflictIncomingLabel", { bg = "#9ca863" })
hi(0, "GitSignsAdd", { link = "GruvboxGreen" })
hi(0, "GitSignsChange", { link = "GruvboxAqua" })
hi(0, "GitSignsDelete", { link = "GruvboxRed" })
hi(0, "GitSignsStagedAdd", { fg = "#5c5d13" })
hi(0, "GitSignsStagedAddLn", { bg = "#62693e" })
hi(0, "GitSignsStagedAddNr", { fg = "#5c5d13" })
hi(0, "GitSignsStagedChange", { fg = "#47603e" })
hi(0, "GitSignsStagedChangeLn", { bg = "#49503b" })
hi(0, "GitSignsStagedChangeNr", { fg = "#47603e" })
hi(0, "GitSignsStagedChangedelete", { fg = "#47603e" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#49503b" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#47603e" })
hi(0, "GitSignsStagedDelete", { fg = "#7d241a" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#7d241a" })
hi(0, "GitSignsStagedTopdelete", { fg = "#7d241a" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#7d241a" })
hi(0, "GruvboxAqua", { fg = "#8ec07c" })
hi(0, "GruvboxAquaBold", { fg = "#8ec07c" })
hi(0, "GruvboxAquaSign", { bg = "#3c3836", fg = "#8ec07c" })
hi(0, "GruvboxAquaUnderline", { sp = "#8ec07c", undercurl = true })
hi(0, "GruvboxBg0", { fg = "#282828" })
hi(0, "GruvboxBg1", { fg = "#3c3836" })
hi(0, "GruvboxBg2", { fg = "#504945" })
hi(0, "GruvboxBg3", { fg = "#665c54" })
hi(0, "GruvboxBg4", { fg = "#7c6f64" })
hi(0, "GruvboxBlue", { fg = "#83a598" })
hi(0, "GruvboxBlueBold", { fg = "#83a598" })
hi(0, "GruvboxBlueSign", { bg = "#3c3836", fg = "#83a598" })
hi(0, "GruvboxBlueUnderline", { sp = "#83a598", undercurl = true })
hi(0, "GruvboxFg0", { fg = "#fbf1c7" })
hi(0, "GruvboxFg1", { fg = "#ebdbb2" })
hi(0, "GruvboxFg2", { fg = "#d5c4a1" })
hi(0, "GruvboxFg3", { fg = "#bdae93" })
hi(0, "GruvboxFg4", { fg = "#a89984" })
hi(0, "GruvboxGray", { fg = "#928374" })
hi(0, "GruvboxGreen", { fg = "#b8bb26" })
hi(0, "GruvboxGreenBold", { fg = "#b8bb26" })
hi(0, "GruvboxGreenSign", { bg = "#3c3836", fg = "#b8bb26" })
hi(0, "GruvboxGreenUnderline", { sp = "#b8bb26", undercurl = true })
hi(0, "GruvboxOrange", { fg = "#fe8019" })
hi(0, "GruvboxOrangeBold", { fg = "#fe8019" })
hi(0, "GruvboxOrangeSign", { bg = "#3c3836", fg = "#fe8019" })
hi(0, "GruvboxOrangeUnderline", { sp = "#fe8019", undercurl = true })
hi(0, "GruvboxPurple", { fg = "#d3869b" })
hi(0, "GruvboxPurpleBold", { fg = "#d3869b" })
hi(0, "GruvboxPurpleSign", { bg = "#3c3836", fg = "#d3869b" })
hi(0, "GruvboxPurpleUnderline", { sp = "#d3869b", undercurl = true })
hi(0, "GruvboxRed", { fg = "#fb4934" })
hi(0, "GruvboxRedBold", { fg = "#fb4934" })
hi(0, "GruvboxRedSign", { bg = "#3c3836", fg = "#fb4934" })
hi(0, "GruvboxRedUnderline", { sp = "#fb4934", undercurl = true })
hi(0, "GruvboxYellow", { fg = "#fabd2f" })
hi(0, "GruvboxYellowBold", { fg = "#fabd2f" })
hi(0, "GruvboxYellowSign", { bg = "#3c3836", fg = "#fabd2f" })
hi(0, "GruvboxYellowUnderline", { sp = "#fabd2f", undercurl = true })
hi(0, "Identifier", { link = "GruvboxBlue" })
hi(0, "IlluminatedWordRead", { link = "LspReferenceRead" })
hi(0, "IlluminatedWordText", { link = "LspReferenceText" })
hi(0, "IlluminatedWordWrite", { link = "LspReferenceWrite" })
hi(0, "IncSearch", { bg = "#282828", fg = "#fe8019", reverse = true })
hi(0, "Include", { link = "GruvboxAqua" })
hi(0, "Keyword", { link = "GruvboxRed" })
hi(0, "Label", { link = "GruvboxRed" })
hi(0, "LineNr", { fg = "#7c6f64" })
hi(0, "LspCodeLens", { link = "GruvboxGray" })
hi(0, "LspInlayHint", { link = "Comment" })
hi(0, "LspReferenceRead", { link = "GruvboxYellowBold" })
hi(0, "LspReferenceText", { link = "GruvboxYellowBold" })
hi(0, "LspReferenceWrite", { link = "GruvboxOrangeBold" })
hi(0, "LspSagaAutoPreview", { link = "GruvboxOrange" })
hi(0, "LspSagaCodeActionBorder", { link = "GruvboxFg1" })
hi(0, "LspSagaCodeActionContent", { fg = "#b8bb26" })
hi(0, "LspSagaCodeActionTitle", { link = "Title" })
hi(0, "LspSagaDefPreviewBorder", { link = "GruvboxBlue" })
hi(0, "LspSagaDiagnosticBorder", { link = "GruvboxPurple" })
hi(0, "LspSagaDiagnosticHeader", { link = "GruvboxGreen" })
hi(0, "LspSagaDiagnosticSource", { link = "GruvboxOrange" })
hi(0, "LspSagaHoverBorder", { link = "GruvboxOrange" })
hi(0, "LspSagaLspFinderBorder", { link = "GruvboxFg1" })
hi(0, "LspSagaRenameBorder", { link = "GruvboxBlue" })
hi(0, "LspSagaSignatureHelpBorder", { link = "GruvboxGreen" })
hi(0, "LspSignatureActiveParameter", { link = "Search" })
hi(0, "Macro", { link = "GruvboxAqua" })
hi(0, "MasonHeader", { link = "MasonHighlightBlockBoldSecondary" })
hi(0, "MasonHeaderSecondary", { link = "MasonHighlightBlockBold" })
hi(0, "MasonHighlight", { link = "GruvboxAqua" })
hi(0, "MasonHighlightBlock", { bg = "#83a598", fg = "#282828" })
hi(0, "MasonHighlightBlockBold", { bg = "#83a598", bold = true, fg = "#282828" })
hi(0, "MasonHighlightBlockBoldSecondary", { bg = "#fabd2f", bold = true, fg = "#282828" })
hi(0, "MasonHighlightBlockSecondary", { bg = "#fabd2f", fg = "#282828" })
hi(0, "MasonHighlightSecondary", { fg = "#fabd2f" })
hi(0, "MasonMuted", { fg = "#a89984" })
hi(0, "MasonMutedBlock", { bg = "#a89984", fg = "#282828" })
hi(0, "MasonMutedBlockBold", { bg = "#a89984", bold = true, fg = "#282828" })
hi(0, "MatchParen", { bg = "#665c54" })
hi(0, "ModeMsg", { link = "GruvboxYellowBold" })
hi(0, "MoreMsg", { link = "GruvboxYellowBold" })
hi(0, "NERDTreeCWD", { link = "GruvboxGreen" })
hi(0, "NERDTreeClosable", { link = "GruvboxOrange" })
hi(0, "NERDTreeDir", { link = "GruvboxAqua" })
hi(0, "NERDTreeDirSlash", { link = "GruvboxAqua" })
hi(0, "NERDTreeExecFile", { link = "GruvboxYellow" })
hi(0, "NERDTreeFile", { link = "GruvboxFg1" })
hi(0, "NERDTreeHelp", { link = "GruvboxFg1" })
hi(0, "NERDTreeOpenable", { link = "GruvboxOrange" })
hi(0, "NERDTreeToggleOff", { link = "GruvboxRed" })
hi(0, "NERDTreeToggleOn", { link = "GruvboxGreen" })
hi(0, "NERDTreeUp", { link = "GruvboxGray" })
hi(0, "NavicIconsArray", { link = "GruvboxOrange" })
hi(0, "NavicIconsBoolean", { link = "GruvboxOrange" })
hi(0, "NavicIconsClass", { link = "GruvboxYellow" })
hi(0, "NavicIconsConstant", { link = "GruvboxOrange" })
hi(0, "NavicIconsConstructor", { link = "GruvboxBlue" })
hi(0, "NavicIconsEnum", { link = "GruvboxPurple" })
hi(0, "NavicIconsEnumMember", { link = "GruvboxYellow" })
hi(0, "NavicIconsEvent", { link = "GruvboxYellow" })
hi(0, "NavicIconsField", { link = "GruvboxPurple" })
hi(0, "NavicIconsFile", { link = "GruvboxBlue" })
hi(0, "NavicIconsFunction", { link = "GruvboxBlue" })
hi(0, "NavicIconsInterface", { link = "GruvboxGreen" })
hi(0, "NavicIconsKey", { link = "GruvboxAqua" })
hi(0, "NavicIconsMethod", { link = "GruvboxBlue" })
hi(0, "NavicIconsModule", { link = "GruvboxOrange" })
hi(0, "NavicIconsNamespace", { link = "GruvboxBlue" })
hi(0, "NavicIconsNull", { link = "GruvboxOrange" })
hi(0, "NavicIconsNumber", { link = "GruvboxOrange" })
hi(0, "NavicIconsObject", { link = "GruvboxOrange" })
hi(0, "NavicIconsOperator", { link = "GruvboxRed" })
hi(0, "NavicIconsPackage", { link = "GruvboxAqua" })
hi(0, "NavicIconsProperty", { link = "GruvboxAqua" })
hi(0, "NavicIconsString", { link = "GruvboxGreen" })
hi(0, "NavicIconsStruct", { link = "GruvboxPurple" })
hi(0, "NavicIconsTypeParameter", { link = "GruvboxRed" })
hi(0, "NavicIconsVariable", { link = "GruvboxPurple" })
hi(0, "NavicSeparator", { link = "GruvboxWhite" })
hi(0, "NavicText", { link = "GruvboxWhite" })
hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
hi(0, "NeogitHunkHeader", { link = "WinBar" })
hi(0, "NeogitHunkHeaderHighlight", { link = "WinBarNC" })
hi(0, "NoiceAttr70", { fg = "#c8c093" })
hi(0, "NoiceCursor", { link = "TermCursor" })
hi(0, "NoiceFormatProgressDone", { bg = "#282828", fg = "#fabd2f", reverse = true })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { link = "GruvboxBg2" })
hi(0, "Normal", { bg = "#282828", fg = "#ebdbb2" })
hi(0, "NormalFloat", { bg = "#3c3836", fg = "#ebdbb2" })
hi(0, "NormalNC", { link = "Normal" })
hi(0, "NotifyDEBUGBorder", { link = "GruvboxBlue" })
hi(0, "NotifyDEBUGIcon", { link = "GruvboxBlue" })
hi(0, "NotifyDEBUGTitle", { link = "GruvboxBlue" })
hi(0, "NotifyERRORBorder", { link = "GruvboxRed" })
hi(0, "NotifyERRORIcon", { link = "GruvboxRed" })
hi(0, "NotifyERRORTitle", { link = "GruvboxRed" })
hi(0, "NotifyINFOBody68", { bg = "#282828", fg = "#ebdbb2" })
hi(0, "NotifyINFOBorder", { link = "GruvboxAqua" })
hi(0, "NotifyINFOBorder68", { fg = "#8ec07c" })
hi(0, "NotifyINFOIcon", { link = "GruvboxAqua" })
hi(0, "NotifyINFOIcon68", { fg = "#8ec07c" })
hi(0, "NotifyINFOTitle", { link = "GruvboxAqua" })
hi(0, "NotifyINFOTitle68", { fg = "#8ec07c" })
hi(0, "NotifyTRACEBorder", { link = "GruvboxGreen" })
hi(0, "NotifyTRACEIcon", { link = "GruvboxGreen" })
hi(0, "NotifyTRACETitle", { link = "GruvboxGreen" })
hi(0, "NotifyWARNBorder", { link = "GruvboxYellow" })
hi(0, "NotifyWARNIcon", { link = "GruvboxYellow" })
hi(0, "NotifyWARNTitle", { link = "GruvboxYellow" })
hi(0, "Number", { link = "GruvboxPurple" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#98971a" })
hi(0, "NvimTreeFolderIcon", { bold = true, fg = "#458588" })
hi(0, "NvimTreeGitDeleted", { fg = "#cc241d" })
hi(0, "NvimTreeGitDirty", { fg = "#d79921" })
hi(0, "NvimTreeGitMerge", { fg = "#b16286" })
hi(0, "NvimTreeGitNew", { fg = "#d79921" })
hi(0, "NvimTreeGitRenamed", { fg = "#b16286" })
hi(0, "NvimTreeGitStaged", { fg = "#d79921" })
hi(0, "NvimTreeImageFile", { fg = "#b16286" })
hi(0, "NvimTreeOpenedFile", { bold = true })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#b16286" })
hi(0, "NvimTreeSpecialFile", { bold = true, fg = "#d79921", underline = true })
hi(0, "NvimTreeSymlink", { fg = "#689d6a" })
hi(0, "NvimTreeWindowPicker", { bg = "#8ec07c" })
hi(0, "Operator", { fg = "#fe8019" })
hi(0, "Pmenu", { bg = "#504945", fg = "#ebdbb2" })
hi(0, "PmenuSbar", { bg = "#504945" })
hi(0, "PmenuSel", { bg = "#83a598", fg = "#504945" })
hi(0, "PmenuThumb", { bg = "#7c6f64" })
hi(0, "PreCondit", { link = "GruvboxAqua" })
hi(0, "PreProc", { link = "GruvboxAqua" })
hi(0, "Question", { link = "GruvboxOrangeBold" })
hi(0, "QuickFixLine", { link = "GruvboxPurple" })
hi(0, "Repeat", { link = "GruvboxRed" })
hi(0, "SagaShadow", { link = "GruvboxBg0" })
hi(0, "Search", { bg = "#282828", fg = "#fabd2f", reverse = true })
hi(0, "SignColumn", { bg = "#3c3836" })
hi(0, "Special", { link = "GruvboxOrange" })
hi(0, "SpecialKey", { link = "GruvboxFg4" })
hi(0, "SpellBad", { link = "GruvboxRedUnderline" })
hi(0, "SpellCap", { link = "GruvboxBlueUnderline" })
hi(0, "SpellLocal", { link = "GruvboxAquaUnderline" })
hi(0, "SpellRare", { link = "GruvboxPurpleUnderline" })
hi(0, "StartifyBracket", { link = "GruvboxFg3" })
hi(0, "StartifyFile", { link = "GruvboxFg1" })
hi(0, "StartifyFooter", { link = "GruvboxBg2" })
hi(0, "StartifyHeader", { link = "GruvboxOrange" })
hi(0, "StartifyNumber", { link = "GruvboxBlue" })
hi(0, "StartifyPath", { link = "GruvboxGray" })
hi(0, "StartifySection", { link = "GruvboxYellow" })
hi(0, "StartifySelect", { link = "Title" })
hi(0, "StartifySlash", { link = "GruvboxGray" })
hi(0, "StartifySpecial", { link = "GruvboxBg2" })
hi(0, "StartifyVar", { link = "StartifyPath" })
hi(0, "Statement", { link = "GruvboxRed" })
hi(0, "StorageClass", { link = "GruvboxOrange" })
hi(0, "String", { fg = "#b8bb26" })
hi(0, "Structure", { link = "GruvboxAqua" })
hi(0, "TSRainbowBlue", { fg = "#83a598" })
hi(0, "TSRainbowGreen", { fg = "#b8bb26" })
hi(0, "TSRainbowOrange", { fg = "#fe8019" })
hi(0, "TSRainbowRed", { fg = "#fb4934" })
hi(0, "TSRainbowViolet", { fg = "#d3869b" })
hi(0, "TSRainbowYellow", { fg = "#fabd2f" })
hi(0, "TabLine", { link = "TabLineFill" })
hi(0, "TabLineFill", { bg = "#3c3836", fg = "#7c6f64" })
hi(0, "TabLineSel", { bg = "#3c3836", fg = "#b8bb26" })
hi(0, "TargetWord", { fg = "#83a598" })
hi(0, "TelescopeBorder", { link = "TelescopeNormal" })
hi(0, "TelescopeMatching", { link = "GruvboxBlue" })
hi(0, "TelescopeMultiSelection", { link = "GruvboxGray" })
hi(0, "TelescopeNormal", { link = "GruvboxFg1" })
hi(0, "TelescopePreviewBorder", { link = "TelescopeNormal" })
hi(0, "TelescopePrompt", { link = "TelescopeNormal" })
hi(0, "TelescopePromptBorder", { link = "TelescopeNormal" })
hi(0, "TelescopePromptPrefix", { link = "GruvboxRed" })
hi(0, "TelescopeResultsBorder", { link = "TelescopeNormal" })
hi(0, "TelescopeSelection", { link = "GruvboxOrangeBold" })
hi(0, "TelescopeSelectionCaret", { link = "GruvboxRed" })
hi(0, "Title", { link = "GruvboxGreenBold" })
hi(0, "Todo", { bg = "#fabd2f", fg = "#282828", italic = true })
hi(0, "Type", { link = "GruvboxYellow" })
hi(0, "Typedef", { link = "GruvboxYellow" })
hi(0, "Underlined", { fg = "#83a598" })
hi(0, "Visual", { bg = "#665c54" })
hi(0, "WarningMsg", { link = "GruvboxRedBold" })
hi(0, "Whitespace", { fg = "#504945" })
hi(0, "WildMenu", { bg = "#504945", fg = "#83a598" })
hi(0, "WinBar", { bg = "#282828", fg = "#a89984" })
hi(0, "WinBarNC", { bg = "#3c3836", fg = "#bdae93" })
hi(0, "WinSeparator", { bg = "#282828", fg = "#665c54" })
hi(0, "cOperator", { link = "GruvboxPurple" })
hi(0, "cStructure", { link = "GruvboxOrange" })
hi(0, "clojureAnonArg", { link = "GruvboxYellow" })
hi(0, "clojureCharacter", { link = "GruvboxAqua" })
hi(0, "clojureCond", { link = "GruvboxOrange" })
hi(0, "clojureDefine", { link = "GruvboxOrange" })
hi(0, "clojureDeref", { link = "GruvboxYellow" })
hi(0, "clojureException", { link = "GruvboxRed" })
hi(0, "clojureFunc", { link = "GruvboxYellow" })
hi(0, "clojureKeyword", { link = "GruvboxBlue" })
hi(0, "clojureMacro", { link = "GruvboxOrange" })
hi(0, "clojureMeta", { link = "GruvboxYellow" })
hi(0, "clojureParen", { link = "GruvboxFg3" })
hi(0, "clojureQuote", { link = "GruvboxYellow" })
hi(0, "clojureRegexp", { link = "GruvboxAqua" })
hi(0, "clojureRegexpCharClass", { fg = "#bdae93" })
hi(0, "clojureRegexpEscape", { link = "GruvboxAqua" })
hi(0, "clojureRegexpMod", { link = "clojureRegexpCharClass" })
hi(0, "clojureRegexpQuantifier", { link = "clojureRegexpCharClass" })
hi(0, "clojureRepeat", { link = "GruvboxYellow" })
hi(0, "clojureSpecial", { link = "GruvboxOrange" })
hi(0, "clojureStringEscape", { link = "GruvboxAqua" })
hi(0, "clojureUnquote", { link = "GruvboxYellow" })
hi(0, "clojureVariable", { link = "GruvboxBlue" })
hi(0, "coffeeBracket", { link = "GruvboxOrange" })
hi(0, "coffeeCurly", { link = "GruvboxOrange" })
hi(0, "coffeeExtendedOp", { link = "GruvboxFg3" })
hi(0, "coffeeParen", { link = "GruvboxFg3" })
hi(0, "coffeeSpecialOp", { link = "GruvboxFg3" })
hi(0, "cppOperator", { link = "GruvboxPurple" })
hi(0, "csBraces", { link = "GruvboxFg1" })
hi(0, "csEndColon", { link = "GruvboxFg1" })
hi(0, "csInterpolationAlignDel", { link = "GruvboxAquaBold" })
hi(0, "csInterpolationDelimiter", { link = "GruvboxFg3" })
hi(0, "csInterpolationFormat", { link = "GruvboxAqua" })
hi(0, "csInterpolationFormatDel", { link = "GruvboxAquaBold" })
hi(0, "csLogicSymbols", { link = "GruvboxFg1" })
hi(0, "csOpSymbols", { link = "GruvboxFg3" })
hi(0, "csParens", { link = "GruvboxFg3" })
hi(0, "cssAnimationProp", { link = "GruvboxAqua" })
hi(0, "cssBackgroundProp", { link = "GruvboxAqua" })
hi(0, "cssBorderOutlineProp", { link = "GruvboxAqua" })
hi(0, "cssBoxProp", { link = "GruvboxAqua" })
hi(0, "cssBraces", { link = "GruvboxBlue" })
hi(0, "cssClassName", { link = "GruvboxGreen" })
hi(0, "cssColor", { link = "GruvboxBlue" })
hi(0, "cssColorProp", { link = "GruvboxAqua" })
hi(0, "cssDimensionProp", { link = "GruvboxAqua" })
hi(0, "cssFlexibleBoxProp", { link = "GruvboxAqua" })
hi(0, "cssFontDescriptorProp", { link = "GruvboxAqua" })
hi(0, "cssFontProp", { link = "GruvboxAqua" })
hi(0, "cssFunctionName", { link = "GruvboxYellow" })
hi(0, "cssGeneratedContentProp", { link = "GruvboxAqua" })
hi(0, "cssIdentifier", { link = "GruvboxOrange" })
hi(0, "cssImportant", { link = "GruvboxGreen" })
hi(0, "cssListProp", { link = "GruvboxAqua" })
hi(0, "cssMarginProp", { link = "GruvboxAqua" })
hi(0, "cssPaddingProp", { link = "GruvboxAqua" })
hi(0, "cssPositioningProp", { link = "GruvboxYellow" })
hi(0, "cssPrintProp", { link = "GruvboxAqua" })
hi(0, "cssRenderProp", { link = "GruvboxAqua" })
hi(0, "cssSelectorOp", { link = "GruvboxBlue" })
hi(0, "cssSelectorOp2", { link = "GruvboxBlue" })
hi(0, "cssTableProp", { link = "GruvboxAqua" })
hi(0, "cssTextProp", { link = "GruvboxAqua" })
hi(0, "cssTransformProp", { link = "GruvboxAqua" })
hi(0, "cssTransitionProp", { link = "GruvboxAqua" })
hi(0, "cssUIProp", { link = "GruvboxYellow" })
hi(0, "cssVendor", { link = "GruvboxFg1" })
hi(0, "debugBreakpoint", { link = "GruvboxRedSign" })
hi(0, "debugPC", { link = "DiffAdd" })
hi(0, "diffAdded", { link = "DiffAdd" })
hi(0, "diffChanged", { link = "DiffChange" })
hi(0, "diffFile", { link = "GruvboxOrange" })
hi(0, "diffIndexLine", { link = "diffChanged" })
hi(0, "diffLine", { link = "GruvboxBlue" })
hi(0, "diffNewFile", { link = "GruvboxYellow" })
hi(0, "diffOldFile", { link = "GruvboxOrange" })
hi(0, "diffRemoved", { link = "DiffDelete" })
hi(0, "docbkKeyword", { link = "GruvboxAquaBold" })
hi(0, "dtdFunction", { link = "GruvboxGray" })
hi(0, "dtdParamEntityDPunct", { link = "GruvboxGray" })
hi(0, "dtdParamEntityPunct", { link = "GruvboxGray" })
hi(0, "dtdTagName", { link = "GruvboxPurple" })
hi(0, "elixirDocString", { link = "Comment" })
hi(0, "elixirInterpolationDelimiter", { link = "GruvboxAqua" })
hi(0, "elixirModuleDeclaration", { link = "GruvboxYellow" })
hi(0, "elixirStringDelimiter", { link = "GruvboxGreen" })
hi(0, "gitcommitDiscardedFile", { link = "GruvboxRed" })
hi(0, "gitcommitSelectedFile", { link = "GruvboxGreen" })
hi(0, "goBuiltins", { link = "GruvboxOrange" })
hi(0, "goConstants", { link = "GruvboxPurple" })
hi(0, "goDeclType", { link = "GruvboxBlue" })
hi(0, "goDeclaration", { link = "GruvboxRed" })
hi(0, "goDirective", { link = "GruvboxAqua" })
hi(0, "haskellAssocType", { link = "GruvboxAqua" })
hi(0, "haskellBacktick", { link = "GruvboxOrange" })
hi(0, "haskellBottom", { link = "GruvboxRedBold" })
hi(0, "haskellConditional", { link = "GruvboxPurple" })
hi(0, "haskellDecl", { link = "GruvboxOrange" })
hi(0, "haskellDeclKeyword", { link = "GruvboxOrange" })
hi(0, "haskellDefault", { link = "GruvboxRed" })
hi(0, "haskellDelimiter", { link = "GruvboxOrange" })
hi(0, "haskellDeriving", { link = "GruvboxPurple" })
hi(0, "haskellFloat", { link = "GruvboxAqua" })
hi(0, "haskellForeignKeywords", { link = "GruvboxGreen" })
hi(0, "haskellIdentifier", { link = "GruvboxAqua" })
hi(0, "haskellImportKeywords", { link = "GruvboxPurpleBold" })
hi(0, "haskellInfix", { link = "GruvboxPurple" })
hi(0, "haskellKeyword", { link = "GruvboxRed" })
hi(0, "haskellLet", { link = "GruvboxRed" })
hi(0, "haskellLiquid", { link = "GruvboxPurpleBold" })
hi(0, "haskellNumber", { link = "GruvboxAqua" })
hi(0, "haskellOperators", { link = "GruvboxPurple" })
hi(0, "haskellPatternKeyword", { link = "GruvboxBlue" })
hi(0, "haskellPragma", { link = "GruvboxRedBold" })
hi(0, "haskellPreProc", { link = "GruvboxFg4" })
hi(0, "haskellQuasiQuoted", { link = "GruvboxBlueBold" })
hi(0, "haskellQuote", { link = "GruvboxGreenBold" })
hi(0, "haskellQuotedType", { link = "GruvboxRed" })
hi(0, "haskellRecursiveDo", { link = "GruvboxPurple" })
hi(0, "haskellSeparator", { link = "GruvboxFg4" })
hi(0, "haskellShebang", { link = "GruvboxYellowBold" })
hi(0, "haskellStatement", { link = "GruvboxPurple" })
hi(0, "haskellTH", { link = "GruvboxAquaBold" })
hi(0, "haskellType", { link = "GruvboxBlue" })
hi(0, "haskellTypeForall", { link = "GruvboxRed" })
hi(0, "haskellTypeRoles", { link = "GruvboxRedBold" })
hi(0, "haskellWhere", { link = "GruvboxRed" })
hi(0, "htmlArg", { link = "GruvboxOrange" })
hi(0, "htmlBold", { bg = "#282828", fg = "#fbf1c7" })
hi(0, "htmlBoldItalic", { bg = "#282828", fg = "#fbf1c7", italic = true })
hi(0, "htmlBoldUnderline", { bg = "#282828", fg = "#fbf1c7" })
hi(0, "htmlBoldUnderlineItalic", { bg = "#282828", fg = "#fbf1c7", italic = true })
hi(0, "htmlEndTag", { link = "GruvboxAquaBold" })
hi(0, "htmlItalic", { bg = "#282828", fg = "#fbf1c7", italic = true })
hi(0, "htmlLink", { fg = "#a89984" })
hi(0, "htmlSpecialChar", { link = "GruvboxRed" })
hi(0, "htmlSpecialTagName", { link = "GruvboxBlue" })
hi(0, "htmlTag", { link = "GruvboxAquaBold" })
hi(0, "htmlTagN", { link = "GruvboxFg1" })
hi(0, "htmlTagName", { link = "GruvboxBlue" })
hi(0, "htmlUnderline", { bg = "#282828", fg = "#fbf1c7" })
hi(0, "htmlUnderlineItalic", { bg = "#282828", fg = "#fbf1c7", italic = true })
hi(0, "iCursor", { link = "Cursor" })
hi(0, "javaAnnotation", { link = "GruvboxBlue" })
hi(0, "javaCommentTitle", { link = "vimCommentTitle" })
hi(0, "javaDocTags", { link = "GruvboxAqua" })
hi(0, "javaOperator", { link = "GruvboxOrange" })
hi(0, "javaParen", { link = "GruvboxFg3" })
hi(0, "javaParen1", { link = "GruvboxFg3" })
hi(0, "javaParen2", { link = "GruvboxFg3" })
hi(0, "javaParen3", { link = "GruvboxFg3" })
hi(0, "javaParen4", { link = "GruvboxFg3" })
hi(0, "javaParen5", { link = "GruvboxFg3" })
hi(0, "javaScriptBraces", { link = "GruvboxFg1" })
hi(0, "javaScriptFunction", { link = "GruvboxAqua" })
hi(0, "javaScriptIdentifier", { link = "GruvboxRed" })
hi(0, "javaScriptMember", { link = "GruvboxBlue" })
hi(0, "javaScriptNull", { link = "GruvboxPurple" })
hi(0, "javaScriptNumber", { link = "GruvboxPurple" })
hi(0, "javaScriptParens", { link = "GruvboxFg3" })
hi(0, "javaVarArg", { link = "GruvboxGreen" })
hi(0, "jsonBraces", { link = "GruvboxFg1" })
hi(0, "jsonKeyword", { link = "GruvboxGreen" })
hi(0, "jsonQuote", { link = "GruvboxGreen" })
hi(0, "jsonString", { link = "GruvboxFg1" })
hi(0, "lCursor", { link = "Cursor" })
hi(0, "luaFunction", { link = "GruvboxAqua" })
hi(0, "luaIn", { link = "GruvboxRed" })
hi(0, "luaTable", { link = "GruvboxOrange" })
hi(0, "mailQuoted1", { link = "GruvboxAqua" })
hi(0, "mailQuoted2", { link = "GruvboxPurple" })
hi(0, "mailQuoted3", { link = "GruvboxYellow" })
hi(0, "mailQuoted4", { link = "GruvboxGreen" })
hi(0, "mailQuoted5", { link = "GruvboxRed" })
hi(0, "mailQuoted6", { link = "GruvboxOrange" })
hi(0, "mailSignature", { link = "Comment" })
hi(0, "markdownBlockquote", { link = "GruvboxGray" })
hi(0, "markdownBold", { fg = "#bdae93" })
hi(0, "markdownBoldItalic", { fg = "#bdae93", italic = true })
hi(0, "markdownCode", { link = "GruvboxAqua" })
hi(0, "markdownCodeBlock", { link = "GruvboxAqua" })
hi(0, "markdownCodeDelimiter", { link = "GruvboxAqua" })
hi(0, "markdownH1", { link = "GruvboxGreenBold" })
hi(0, "markdownH2", { link = "GruvboxGreenBold" })
hi(0, "markdownH3", { link = "GruvboxYellowBold" })
hi(0, "markdownH4", { link = "GruvboxYellowBold" })
hi(0, "markdownH5", { link = "GruvboxYellow" })
hi(0, "markdownH6", { link = "GruvboxYellow" })
hi(0, "markdownHeadingDelimiter", { link = "GruvboxOrange" })
hi(0, "markdownHeadingRule", { link = "GruvboxGray" })
hi(0, "markdownIdDeclaration", { link = "markdownLinkText" })
hi(0, "markdownItalic", { fg = "#bdae93", italic = true })
hi(0, "markdownLinkDelimiter", { link = "GruvboxFg3" })
hi(0, "markdownLinkText", { fg = "#928374" })
hi(0, "markdownLinkTextDelimiter", { link = "GruvboxFg3" })
hi(0, "markdownListMarker", { link = "GruvboxGray" })
hi(0, "markdownOrderedListMarker", { link = "GruvboxGray" })
hi(0, "markdownRule", { link = "GruvboxGray" })
hi(0, "markdownUrl", { link = "GruvboxPurple" })
hi(0, "markdownUrlDelimiter", { link = "GruvboxFg3" })
hi(0, "markdownUrlTitleDelimiter", { link = "GruvboxGreen" })
hi(0, "moonExtendedOp", { link = "GruvboxFg3" })
hi(0, "moonFunction", { link = "GruvboxFg3" })
hi(0, "moonObject", { link = "GruvboxYellow" })
hi(0, "moonSpecialOp", { link = "GruvboxFg3" })
hi(0, "netrwClassify", { link = "GruvboxAqua" })
hi(0, "netrwCmdSep", { link = "GruvboxFg3" })
hi(0, "netrwComment", { link = "GruvboxGray" })
hi(0, "netrwDir", { link = "GruvboxAqua" })
hi(0, "netrwExe", { link = "GruvboxYellow" })
hi(0, "netrwHelpCmd", { link = "GruvboxAqua" })
hi(0, "netrwLink", { link = "GruvboxGray" })
hi(0, "netrwList", { link = "GruvboxBlue" })
hi(0, "netrwSymLink", { link = "GruvboxFg1" })
hi(0, "netrwVersion", { link = "GruvboxGreen" })
hi(0, "objcDirective", { link = "GruvboxBlue" })
hi(0, "objcTypeModifier", { link = "GruvboxRed" })
hi(0, "ocamlArrow", { link = "GruvboxOrange" })
hi(0, "ocamlConstructor", { link = "GruvboxOrange" })
hi(0, "ocamlInfixOpKeyword", { link = "GruvboxRed" })
hi(0, "ocamlKeyChar", { link = "GruvboxOrange" })
hi(0, "ocamlOperator", { link = "GruvboxFg1" })
hi(0, "purescriptAsKeyword", { link = "GruvboxAqua" })
hi(0, "purescriptBacktick", { link = "GruvboxOrange" })
hi(0, "purescriptConditional", { link = "GruvboxOrange" })
hi(0, "purescriptConstructor", { link = "GruvboxFg1" })
hi(0, "purescriptDelimiter", { link = "GruvboxFg4" })
hi(0, "purescriptFunction", { link = "GruvboxFg1" })
hi(0, "purescriptHidingKeyword", { link = "GruvboxAqua" })
hi(0, "purescriptImportKeyword", { link = "GruvboxAqua" })
hi(0, "purescriptModuleKeyword", { link = "GruvboxAqua" })
hi(0, "purescriptModuleName", { link = "GruvboxFg1" })
hi(0, "purescriptOperator", { link = "GruvboxBlue" })
hi(0, "purescriptStructure", { link = "GruvboxAqua" })
hi(0, "purescriptType", { link = "GruvboxFg1" })
hi(0, "purescriptTypeVar", { link = "GruvboxFg1" })
hi(0, "purescriptWhere", { link = "GruvboxAqua" })
hi(0, "pythonBoolean", { link = "GruvboxPurple" })
hi(0, "pythonBuiltin", { link = "GruvboxOrange" })
hi(0, "pythonBuiltinFunc", { link = "GruvboxOrange" })
hi(0, "pythonBuiltinObj", { link = "GruvboxOrange" })
hi(0, "pythonCoding", { link = "GruvboxBlue" })
hi(0, "pythonConditional", { link = "GruvboxRed" })
hi(0, "pythonDecorator", { link = "GruvboxRed" })
hi(0, "pythonDot", { link = "GruvboxFg3" })
hi(0, "pythonDottedName", { link = "GruvboxGreenBold" })
hi(0, "pythonException", { link = "GruvboxRed" })
hi(0, "pythonExceptions", { link = "GruvboxPurple" })
hi(0, "pythonFunction", { link = "GruvboxAqua" })
hi(0, "pythonImport", { link = "GruvboxBlue" })
hi(0, "pythonInclude", { link = "GruvboxBlue" })
hi(0, "pythonOperator", { link = "GruvboxRed" })
hi(0, "pythonRepeat", { link = "GruvboxRed" })
hi(0, "pythonRun", { link = "GruvboxBlue" })
hi(0, "rubyDefinedOperator", { link = "rubyKeyword" })
hi(0, "rubyInterpolationDelimiter", { link = "GruvboxAqua" })
hi(0, "rubyStringDelimiter", { link = "GruvboxGreen" })
hi(0, "rustCommentLineDoc", { link = "Comment" })
hi(0, "rustDefault", { link = "GruvboxAqua" })
hi(0, "rustEnum", { link = "GruvboxAqua" })
hi(0, "rustEscape", { link = "GruvboxAqua" })
hi(0, "rustModPathSep", { link = "GruvboxFg2" })
hi(0, "rustSigil", { link = "GruvboxOrange" })
hi(0, "rustStringContinuation", { link = "GruvboxAqua" })
hi(0, "rustStructure", { link = "GruvboxAqua" })
hi(0, "scalaCapitalWord", { link = "GruvboxFg1" })
hi(0, "scalaCaseFollowing", { link = "GruvboxFg1" })
hi(0, "scalaInstanceDeclaration", { link = "GruvboxFg1" })
hi(0, "scalaInterpolation", { link = "GruvboxAqua" })
hi(0, "scalaKeyword", { link = "GruvboxRed" })
hi(0, "scalaKeywordModifier", { link = "GruvboxRed" })
hi(0, "scalaNameDefinition", { link = "GruvboxFg1" })
hi(0, "scalaOperator", { link = "GruvboxFg1" })
hi(0, "scalaSpecial", { link = "GruvboxAqua" })
hi(0, "scalaTypeDeclaration", { link = "GruvboxYellow" })
hi(0, "scalaTypeExtension", { link = "GruvboxFg1" })
hi(0, "scalaTypeTypePostDeclaration", { link = "GruvboxYellow" })
hi(0, "typescriptAjaxMethods", { link = "GruvboxFg1" })
hi(0, "typescriptBraces", { link = "GruvboxFg1" })
hi(0, "typescriptDOMObjects", { link = "GruvboxFg1" })
hi(0, "typescriptDocParam", { link = "Comment" })
hi(0, "typescriptDocSeeTag", { link = "Comment" })
hi(0, "typescriptDocTags", { link = "vimCommentTitle" })
hi(0, "typescriptEndColons", { link = "GruvboxFg1" })
hi(0, "typescriptFuncKeyword", { link = "GruvboxAqua" })
hi(0, "typescriptGlobalObjects", { link = "GruvboxFg1" })
hi(0, "typescriptHtmlElemProperties", { link = "GruvboxFg1" })
hi(0, "typescriptIdentifier", { link = "GruvboxOrange" })
hi(0, "typescriptInterpolationDelimiter", { link = "GruvboxAqua" })
hi(0, "typescriptLabel", { link = "GruvboxAqua" })
hi(0, "typescriptLogicSymbols", { link = "GruvboxFg1" })
hi(0, "typescriptNull", { link = "GruvboxPurple" })
hi(0, "typescriptOpSymbols", { link = "GruvboxFg3" })
hi(0, "typescriptParens", { link = "GruvboxFg3" })
hi(0, "typescriptReserved", { link = "GruvboxAqua" })
hi(0, "vCursor", { link = "Cursor" })
hi(0, "xmlAttrib", { link = "GruvboxOrange" })
hi(0, "xmlAttribPunct", { link = "GruvboxGray" })
hi(0, "xmlCdataCdata", { link = "GruvboxPurple" })
hi(0, "xmlCdataStart", { link = "GruvboxGray" })
hi(0, "xmlDocTypeDecl", { link = "GruvboxGray" })
hi(0, "xmlDocTypeKeyword", { link = "GruvboxPurple" })
hi(0, "xmlEndTag", { link = "GruvboxAquaBold" })
hi(0, "xmlEntity", { link = "GruvboxRed" })
hi(0, "xmlEntityPunct", { link = "GruvboxRed" })
hi(0, "xmlEqual", { link = "GruvboxBlue" })
hi(0, "xmlProcessingDelim", { link = "GruvboxGray" })
hi(0, "xmlTag", { link = "GruvboxAquaBold" })
hi(0, "xmlTagName", { link = "GruvboxBlue" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#282828"
g.terminal_color_1 = "#cc241d"
g.terminal_color_2 = "#98971a"
g.terminal_color_3 = "#d79921"
g.terminal_color_4 = "#458588"
g.terminal_color_5 = "#b16286"
g.terminal_color_6 = "#689d6a"
g.terminal_color_7 = "#a89984"
g.terminal_color_8 = "#928374"
g.terminal_color_9 = "#fb4934"
g.terminal_color_10 = "#b8bb26"
g.terminal_color_11 = "#fabd2f"
g.terminal_color_12 = "#83a598"
g.terminal_color_13 = "#d3869b"
g.terminal_color_14 = "#8ec07c"
g.terminal_color_15 = "#ebdbb2"
