-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "kanagawa"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@constructor", { fg = "#949fb5" })
hi(0, "@constructor.lua", { fg = "#8992a7" })
hi(0, "@exception", { bold = true, fg = "#c4746e" })
hi(0, "@keyword.luap", { link = "@string.regex" })
hi(0, "@keyword.operator", { bold = true, fg = "#c4746e" })
hi(0, "@keyword.return", { fg = "#c4746e", italic = true })
hi(0, "@lsp.mod.readonly", { link = "Constant" })
hi(0, "@lsp.mod.typeHint", { link = "Type" })
hi(0, "@lsp.type.builtinConstant", { link = "@constant.builtin" })
hi(0, "@lsp.type.comment", {})
hi(0, "@lsp.type.magicFunction", { link = "@function.builtin" })
hi(0, "@lsp.type.method", { link = "@method" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.selfParameter", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.function.builtin", { link = "@function.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.function.readonly", { bold = true, fg = "#8ba4b0" })
hi(0, "@lsp.typemod.keyword.documentation", { link = "Special" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.controlFlow", { link = "@exception" })
hi(0, "@lsp.typemod.operator.injected", { link = "Operator" })
hi(0, "@lsp.typemod.string.injected", { link = "String" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "Special" })
hi(0, "@lsp.typemod.variable.global", { link = "Constant" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@lsp.typemod.variable.static", { link = "Constant" })
hi(0, "@parameter", { fg = "#a6a69c" })
hi(0, "@punctuation.bracket", { fg = "#9e9b93" })
hi(0, "@punctuation.delimiter", { fg = "#9e9b93" })
hi(0, "@punctuation.special", { fg = "#949fb5" })
hi(0, "@string.escape", { bold = true, fg = "#c4746e" })
hi(0, "@string.regex", { fg = "#c4746e" })
hi(0, "@symbol", { fg = "#c4b28a" })
hi(0, "@tag.attribute", { fg = "#c4b28a" })
hi(0, "@tag.delimiter", { fg = "#9e9b93" })
hi(0, "@text.danger", { bg = "#e82424", bold = true, fg = "#c5c9c5" })
hi(0, "@text.diff.add", { fg = "#76946a" })
hi(0, "@text.diff.delete", { fg = "#c34043" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.environment", { link = "Keyword" })
hi(0, "@text.environment.name", { link = "String" })
hi(0, "@text.literal", { link = "String" })
hi(0, "@text.math", { link = "Constant" })
hi(0, "@text.note", { bg = "#6a9589", bold = true, fg = "#223249" })
hi(0, "@text.quote", { link = "@parameter" })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { link = "Function" })
hi(0, "@text.warning", { bg = "#ff9e3b", bold = true, fg = "#223249" })
hi(0, "@variable", { fg = "#c5c9c5" })
hi(0, "@variable.builtin", { fg = "#c4746e", italic = true })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { bold = true, fg = "#b6927b" })
hi(0, "Character", { link = "String" })
hi(0, "CmpCompletion", { link = "Pmenu" })
hi(0, "CmpCompletionBorder", { bg = "#223249", fg = "#2d4f67" })
hi(0, "CmpCompletionSbar", { link = "PmenuSbar" })
hi(0, "CmpCompletionSel", { bg = "#2d4f67" })
hi(0, "CmpCompletionThumb", { link = "PmenuThumb" })
hi(0, "CmpDocumentation", { link = "NormalFloat" })
hi(0, "CmpDocumentationBorder", { link = "FloatBorder" })
hi(0, "CmpItemAbbr", { fg = "#dcd7ba" })
hi(0, "CmpItemAbbrDefault", { fg = "#dcd7ba" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#737c73", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#737c73" })
hi(0, "CmpItemAbbrMatch", { fg = "#8ba4b0" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#dcd7ba" })
hi(0, "CmpItemAbbrMatchFuzzy", { link = "CmpItemAbbrMatch" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#dcd7ba" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { link = "Constant" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { link = "@constructor" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { link = "String" })
hi(0, "CmpItemKindDefault", { fg = "#949fb5" })
hi(0, "CmpItemKindEnum", { link = "Type" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { link = "Constant" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { link = "@field" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { link = "Directory" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "Type" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { link = "@keyword" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "@include" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { link = "@property" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { link = "Type" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#949fb5" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { link = "Type" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { fg = "#dcd7ba" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { link = "Type" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { link = "String" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#c8c093" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#737c73" })
hi(0, "CmpItemMenuDefault", { fg = "#dcd7ba" })
hi(0, "ColorColumn", { bg = "#282727" })
hi(0, "Comment", { fg = "#737c73", italic = true })
hi(0, "Conceal", { bold = true, fg = "#7a8382" })
hi(0, "Constant", { fg = "#b6927b" })
hi(0, "CurSearch", { bg = "#2d4f67", bold = true, fg = "#c5c9c5" })
hi(0, "Cursor", { bg = "#c5c9c5", fg = "#181616" })
hi(0, "CursorColumn", { link = "CursorLine" })
hi(0, "CursorLine", { bg = "#393836" })
hi(0, "CursorLineNr", { bg = "#282727", bold = true, fg = "#ff9e3b" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#c4b28a" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { fg = "#658594" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { fg = "#54546d" })
hi(0, "DapUIFloatBorder", { fg = "#54546d" })
hi(0, "DapUILineNumber", { fg = "#949fb5" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#949fb5" })
hi(0, "DapUINormalNC", { bg = "#181616", fg = "#c5c9c5" })
hi(0, "DapUIPlayPause", { fg = "#8a9a7b" })
hi(0, "DapUIPlayPauseNC", { bg = "#12120f", fg = "#8a9a7b" })
hi(0, "DapUIRestart", { fg = "#8a9a7b" })
hi(0, "DapUIRestartNC", { bg = "#12120f", fg = "#8a9a7b" })
hi(0, "DapUIScope", { link = "Special" })
hi(0, "DapUISource", { fg = "#c4746e" })
hi(0, "DapUIStepBack", { fg = "#949fb5" })
hi(0, "DapUIStepBackNC", { bg = "#12120f", fg = "#949fb5" })
hi(0, "DapUIStepInto", { fg = "#949fb5" })
hi(0, "DapUIStepIntoNC", { bg = "#12120f", fg = "#949fb5" })
hi(0, "DapUIStepOut", { fg = "#949fb5" })
hi(0, "DapUIStepOutNC", { bg = "#12120f", fg = "#949fb5" })
hi(0, "DapUIStepOver", { fg = "#949fb5" })
hi(0, "DapUIStepOverNC", { bg = "#12120f", fg = "#949fb5" })
hi(0, "DapUIStop", { fg = "#e82424" })
hi(0, "DapUIStopNC", { bg = "#12120f", fg = "#e82424" })
hi(0, "DapUIStoppedThread", { fg = "#949fb5" })
hi(0, "DapUIThread", { fg = "#c4b28a" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIUnavailable", { fg = "#737c73" })
hi(0, "DapUIUnavailableNC", { bg = "#12120f", fg = "#737c73" })
hi(0, "DapUIWatchesEmpty", { fg = "#e82424" })
hi(0, "DapUIWatchesError", { fg = "#e82424" })
hi(0, "DapUIWatchesValue", { fg = "#c4b28a" })
hi(0, "DapUIWinSelect", { bold = true, ctermfg = 14, fg = "#00f1f5" })
hi(0, "DashboardCenter", { fg = "#c4b28a" })
hi(0, "DashboardDesc", { fg = "#c4b28a" })
hi(0, "DashboardFooter", { fg = "#737c73" })
hi(0, "DashboardHeader", { fg = "#c34043" })
hi(0, "DashboardIcon", { fg = "#7a8382" })
hi(0, "DashboardKey", { fg = "#949fb5" })
hi(0, "DashboardShortCut", { fg = "#949fb5" })
hi(0, "Delimiter", { fg = "#9e9b93" })
hi(0, "DiagnosticError", { fg = "#e82424" })
hi(0, "DiagnosticHint", { fg = "#6a9589" })
hi(0, "DiagnosticInfo", { fg = "#658594" })
hi(0, "DiagnosticOk", { fg = "#98bb6c" })
hi(0, "DiagnosticSignError", { bg = "#282727", fg = "#e82424" })
hi(0, "DiagnosticSignHint", { bg = "#282727", fg = "#6a9589" })
hi(0, "DiagnosticSignInfo", { bg = "#282727", fg = "#658594" })
hi(0, "DiagnosticSignWarn", { bg = "#282727", fg = "#ff9e3b" })
hi(0, "DiagnosticUnderlineError", { sp = "#e82424", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#6a9589", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#658594", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#ff9e3b", undercurl = true })
hi(0, "DiagnosticWarn", { fg = "#ff9e3b" })
hi(0, "DiffAdd", { bg = "#2b3328" })
hi(0, "DiffChange", { bg = "#252535" })
hi(0, "DiffDelete", { bg = "#43242b", fg = "#c34043" })
hi(0, "DiffText", { bg = "#49443c" })
hi(0, "Directory", { fg = "#8ba4b0" })
hi(0, "DressingSelectIdx", { link = "Special" })
hi(0, "EndOfBuffer", { fg = "#181616" })
hi(0, "Error", { fg = "#e82424" })
hi(0, "ErrorMsg", { fg = "#e82424" })
hi(0, "Exception", { fg = "#c4746e" })
hi(0, "FloatBorder", { bg = "#0d0c0c", fg = "#54546d" })
hi(0, "FloatTitle", { bg = "#0d0c0c", bold = true, fg = "#7a8382" })
hi(0, "FloatermBorder", { bg = "#181616", fg = "#54546d" })
hi(0, "FoldColumn", { bg = "#282727", fg = "#625e5a" })
hi(0, "Folded", { bg = "#282727", fg = "#7a8382" })
hi(0, "Function", { fg = "#8ba4b0" })
hi(0, "FzfLuaBufFlagAlt", { fg = "#98f5ff" })
hi(0, "FzfLuaBufFlagCur", { fg = "#ff4040" })
hi(0, "FzfLuaBufLineNr", { fg = "#00fa9a" })
hi(0, "FzfLuaBufName", { fg = "#ffbbff" })
hi(0, "FzfLuaBufNr", { fg = "#ffebcd" })
hi(0, "FzfLuaHeaderBind", { fg = "#ffebcd" })
hi(0, "FzfLuaHeaderText", { fg = "#ff4040" })
hi(0, "FzfLuaTabMarker", { bold = true, fg = "#ffebcd" })
hi(0, "FzfLuaTabTitle", { bold = true, fg = "#b0e2ff" })
hi(0, "GitConflictAncestor", { bg = "#68217a", bold = true })
hi(0, "GitConflictAncestorLabel", { bg = "#a634c3" })
hi(0, "GitConflictCurrent", { bg = "#49443c", bold = true })
hi(0, "GitConflictCurrentLabel", { bg = "#746c60" })
hi(0, "GitConflictIncoming", { bg = "#2b3328", bold = true })
hi(0, "GitConflictIncomingLabel", { bg = "#445140" })
hi(0, "GitSignsAdd", { bg = "#282727", fg = "#76946a" })
hi(0, "GitSignsChange", { bg = "#282727", fg = "#dca561" })
hi(0, "GitSignsDelete", { bg = "#282727", fg = "#c34043" })
hi(0, "GitSignsStagedAdd", { bg = "#282727", fg = "#3b4a35" })
hi(0, "GitSignsStagedAddLn", { bg = "#2b3328" })
hi(0, "GitSignsStagedAddNr", { bg = "#282727", fg = "#3b4a35" })
hi(0, "GitSignsStagedChange", { bg = "#282727", fg = "#6e5230" })
hi(0, "GitSignsStagedChangeLn", { bg = "#252535" })
hi(0, "GitSignsStagedChangeNr", { bg = "#282727", fg = "#6e5230" })
hi(0, "GitSignsStagedChangedelete", { bg = "#282727", fg = "#6e5230" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#252535" })
hi(0, "GitSignsStagedChangedeleteNr", { bg = "#282727", fg = "#6e5230" })
hi(0, "GitSignsStagedDelete", { bg = "#282727", fg = "#612021" })
hi(0, "GitSignsStagedDeleteNr", { bg = "#282727", fg = "#612021" })
hi(0, "GitSignsStagedTopdelete", { bg = "#282727", fg = "#612021" })
hi(0, "GitSignsStagedTopdeleteNr", { bg = "#282727", fg = "#612021" })
hi(0, "Identifier", { fg = "#c4b28a" })
hi(0, "Ignore", { link = "NonText" })
hi(0, "IncSearch", { bg = "#ff9e3b", fg = "#223249" })
hi(0, "IndentBlanklineChar", { fg = "#625e5a" })
hi(0, "IndentBlanklineContextChar", { fg = "#7a8382" })
hi(0, "IndentBlanklineContextStart", { sp = "#7a8382", underline = true })
hi(0, "IndentBlanklineSpaceChar", { fg = "#625e5a" })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#625e5a" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#8992a7", italic = true })
hi(0, "LazyProgressTodo", { fg = "#625e5a" })
hi(0, "LineNr", { bg = "#282727", fg = "#625e5a" })
hi(0, "LspCodeLens", { fg = "#737c73" })
hi(0, "LspReferenceRead", { link = "LspReferenceText" })
hi(0, "LspReferenceText", { bg = "#49443c" })
hi(0, "LspReferenceWrite", { bg = "#49443c", underline = true })
hi(0, "LspSignatureActiveParameter", { fg = "#ff9e3b" })
hi(0, "MatchParen", { bold = true, fg = "#ff9e3b" })
hi(0, "MiniIndentscopeSymbol", { link = "Comment" })
hi(0, "ModeMsg", { bold = true, fg = "#ff9e3b" })
hi(0, "MoreMsg", { fg = "#658594" })
hi(0, "MsgArea", { fg = "#c8c093" })
hi(0, "MsgSeparator", { bg = "#0d0c0c" })
hi(0, "NeoTreeGitAdded", { fg = "#76946a" })
hi(0, "NeoTreeGitConflict", { fg = "#e82424" })
hi(0, "NeoTreeGitDeleted", { fg = "#c34043" })
hi(0, "NeoTreeGitModified", { fg = "#dca561" })
hi(0, "NeoTreeGitStaged", { fg = "#76946a" })
hi(0, "NeoTreeIndentMarker", { link = "NonText" })
hi(0, "NeoTreeModified", { link = "String" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#c4b28a" })
hi(0, "NeoTreeTabActive", { link = "TabLineSel" })
hi(0, "NeoTreeTabInactive", { link = "TabLine" })
hi(0, "NeoTreeTabSeparatorActive", { link = "NeoTreeTabActive" })
hi(0, "NeoTreeTabSeparatorInactive", { link = "NeoTreeTabInactive" })
hi(0, "NeogitDiffAddHighlight", { bg = "#2b3328" })
hi(0, "NeogitDiffContextHighlight", { bg = "#252535" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#43242b" })
hi(0, "NeogitHunkHeader", { fg = "#8ba4b0" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#252535", fg = "#b6927b" })
hi(0, "NoiceAttr70", { fg = "#c8c093" })
hi(0, "NoiceFormatProgressDone", { bg = "#2d4f67", fg = "#c5c9c5" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = "#625e5a" })
hi(0, "Normal", { bg = "#181616", fg = "#c5c9c5" })
hi(0, "NormalFloat", { bg = "#0d0c0c", fg = "#c8c093" })
hi(0, "NormalNC", { bg = "#12120f", fg = "#c8c093" })
hi(0, "NotifyBackground", { bg = "#181616" })
hi(0, "NotifyDEBUGBorder", { link = "Debug" })
hi(0, "NotifyDEBUGIcon", { link = "Debug" })
hi(0, "NotifyDEBUGTitle", { link = "Debug" })
hi(0, "NotifyERRORBorder", { link = "DiagnosticError" })
hi(0, "NotifyERRORIcon", { link = "DiagnosticError" })
hi(0, "NotifyERRORTitle", { link = "DiagnosticError" })
hi(0, "NotifyHINTBorder", { link = "DiagnosticHint" })
hi(0, "NotifyHINTIcon", { link = "DiagnosticHint" })
hi(0, "NotifyHINTTitle", { link = "DiagnosticHint" })
hi(0, "NotifyINFOBorder", { link = "DiagnosticInfo" })
hi(0, "NotifyINFOIcon", { link = "DiagnosticInfo" })
hi(0, "NotifyINFOTitle", { link = "DiagnosticInfo" })
hi(0, "NotifyTRACEBorder", { link = "Comment" })
hi(0, "NotifyTRACEIcon", { link = "Comment" })
hi(0, "NotifyTRACETitle", { link = "Comment" })
hi(0, "NotifyWARNBorder", { link = "DiagnosticWarn" })
hi(0, "NotifyWARNIcon", { link = "DiagnosticWarn" })
hi(0, "NotifyWARNTitle", { link = "DiagnosticWarn" })
hi(0, "Number", { fg = "#a292a3" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#8a9a7b" })
hi(0, "NvimTreeFolderName", { link = "Directory" })
hi(0, "NvimTreeGitDeleted", { fg = "#c34043" })
hi(0, "NvimTreeGitDirty", { fg = "#dca561" })
hi(0, "NvimTreeGitNew", { fg = "#76946a" })
hi(0, "NvimTreeGitStaged", { fg = "#76946a" })
hi(0, "NvimTreeImageFile", { fg = "#c4746e" })
hi(0, "NvimTreeNormal", { link = "Normal" })
hi(0, "NvimTreeNormalNC", { link = "NvimTreeNormal" })
hi(0, "NvimTreeOpenedFile", { fg = "#949fb5", italic = true })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#c4b28a" })
hi(0, "NvimTreeSpecialFile", { fg = "#949fb5" })
hi(0, "NvimTreeSymlink", { link = "Type" })
hi(0, "NvimTreeWinSeparator", { link = "WinSeparator" })
hi(0, "NvimTreeWindowPicker", { bg = "#1d1c19", bold = true, fg = "#949fb5" })
hi(0, "Operator", { fg = "#c4746e" })
hi(0, "Pmenu", { bg = "#223249", fg = "#dcd7ba" })
hi(0, "PmenuSbar", { bg = "#223249" })
hi(0, "PmenuSel", { bg = "#2d4f67" })
hi(0, "PmenuThumb", { bg = "#2d4f67" })
hi(0, "PreProc", { fg = "#c4746e" })
hi(0, "Question", { link = "MoreMsg" })
hi(0, "QuickFixLine", { bg = "#282727" })
hi(0, "Search", { bg = "#2d4f67", fg = "#c5c9c5" })
hi(0, "SignColumn", { bg = "#282727", fg = "#7a8382" })
hi(0, "Special", { fg = "#949fb5" })
hi(0, "SpecialKey", { fg = "#7a8382" })
hi(0, "SpellBad", { sp = "#e82424", undercurl = true })
hi(0, "SpellCap", { sp = "#ff9e3b", undercurl = true })
hi(0, "SpellLocal", { sp = "#ff9e3b", undercurl = true })
hi(0, "SpellRare", { sp = "#ff9e3b", undercurl = true })
hi(0, "Statement", { bold = true, fg = "#8992a7" })
hi(0, "String", { fg = "#8a9a7b" })
hi(0, "Substitute", { bg = "#c34043", fg = "#c5c9c5" })
hi(0, "TabLine", { bg = "#0d0c0c", fg = "#7a8382" })
hi(0, "TabLineFill", { bg = "#181616" })
hi(0, "TabLineSel", { bg = "#282727", fg = "#c8c093" })
hi(0, "TelescopeBorder", { bg = "#181616", fg = "#54546d" })
hi(0, "TelescopeResultsClass", { link = "Structure" })
hi(0, "TelescopeResultsField", { link = "@field" })
hi(0, "TelescopeResultsMethod", { link = "Function" })
hi(0, "TelescopeResultsStruct", { link = "Structure" })
hi(0, "TelescopeResultsVariable", { link = "@variable" })
hi(0, "TelescopeSelection", { link = "CursorLine" })
hi(0, "TelescopeSelectionCaret", { link = "CursorLineNr" })
hi(0, "TelescopeTitle", { fg = "#7a8382" })
hi(0, "Title", { bold = true, fg = "#8ba4b0" })
hi(0, "Todo", { bg = "#658594", bold = true, fg = "#223249" })
hi(0, "TreesitterContext", { link = "Folded" })
hi(0, "TreesitterContextLineNumber", { bg = "#282727", fg = "#7a8382" })
hi(0, "Type", { fg = "#8ea4a2" })
hi(0, "Underlined", { fg = "#949fb5", underline = true })
hi(0, "Visual", { bg = "#223249" })
hi(0, "WarningMsg", { fg = "#ff9e3b" })
hi(0, "Whitespace", { fg = "#625e5a" })
hi(0, "WildMenu", { link = "Pmenu" })
hi(0, "WinBar", { fg = "#c8c093" })
hi(0, "WinBarNC", { bg = "#12120f", fg = "#c8c093" })
hi(0, "WinSeparator", { bg = "#12120f", fg = "#0d0c0c" })
hi(0, "debugBreakpoint", { bg = "#282727", fg = "#949fb5" })
hi(0, "debugPC", { bg = "#43242b" })
hi(0, "diffAdded", { fg = "#76946a" })
hi(0, "diffChanged", { fg = "#dca561" })
hi(0, "diffDeleted", { fg = "#c34043" })
hi(0, "diffNewFile", { fg = "#76946a" })
hi(0, "diffOldFile", { fg = "#c34043" })
hi(0, "diffRemoved", { fg = "#c34043" })
hi(0, "healthError", { fg = "#e82424" })
hi(0, "healthSuccess", { fg = "#98bb6c" })
hi(0, "healthWarning", { fg = "#ff9e3b" })
hi(0, "lCursor", { link = "Cursor" })
hi(0, "markdownCode", { fg = "#8a9a7b" })
hi(0, "markdownCodeBlock", { fg = "#8a9a7b" })
hi(0, "qfFileName", { link = "Directory" })
hi(0, "qfLineNr", { link = "LineNr" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#0d0c0c"
g.terminal_color_1 = "#c4746e"
g.terminal_color_2 = "#8a9a7b"
g.terminal_color_3 = "#c4b28a"
g.terminal_color_4 = "#8ba4b0"
g.terminal_color_5 = "#a292a3"
g.terminal_color_6 = "#8ea4a2"
g.terminal_color_7 = "#c8c093"
g.terminal_color_8 = "#a6a69c"
g.terminal_color_9 = "#e46876"
g.terminal_color_10 = "#87a987"
g.terminal_color_11 = "#e6c384"
g.terminal_color_12 = "#7fb4ca"
g.terminal_color_13 = "#938aa9"
g.terminal_color_14 = "#7aa89f"
g.terminal_color_15 = "#c5c9c5"
