return {
	{
		"nvim-treesitter/nvim-treesitter",
		lazy = false,
		config = function()
			require("nvim-treesitter.configs").setup({
				ensure_installed = {
					"bash",
					"c",
					"cmake",
					"cpp",
					"css",
					"dockerfile",
					"git_config",
					"git_rebase",
					"gitattributes",
					"gitcommit",
					"gitignore",
					"go",
					"html",
					"java",
					"javascript",
					"json",
                    "jsonc",
					"lua",
					"markdown",
					"markdown_inline",
                    "make",
					"norg",
					"nix",
					"python",
					"rust",
					"scss",
					"sql",
					"toml",
					"typescript",
					"vue",
					"yaml",
					"yuck",
				},
				highlight = {
					enable = true,
					use_languagetree = true,
				},
			})
		end,
		-- dependencies = { "nvim-treesitter/nvim-treesitter-context" },
	},

	{ "nvim-treesitter/playground", cmd = { "TSHighlightCapturesUnderCursor", "TSPlaygroundToggle" } },
}
